/*
 * maelys-policy: the agent-cli/v2 command line of Maelys Sandbox Policy,
 * built on libmaelys_cli. It only reads and writes files; the policy work is
 * libmaelys-mir's.
 */
#include <maelys/cli.h>
#include <maelys/mir.h>
#include <maelys/sandbox_policy.h>

#include "policy_schemas.h" /* generated by maelys-cli-embed from cli/schemas/ */

#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>

/* ---- shared helpers ------------------------------------------------------- */

static int read_input(maelys_cli_context_t *context, const char *path,
                      unsigned char **out, size_t *out_size) {
  if (maelys_cli_read_regular_file(path, 0u, MAELYS_MIR_MAX_BYTES, out,
                                   out_size) == 0)
    return 0;
  int saved = errno;
  if (saved == EFBIG)
    return maelys_cli_fail(context, MAELYS_CLI_CODE_VALIDATION_FAILED,
                           "Policy inputs are limited to 1 MiB.",
                           "%s exceeds %u bytes.", path, MAELYS_MIR_MAX_BYTES);
  return maelys_cli_fail_file(context, saved, NULL, path);
}

/* A library failure the input caused is a validation failure; anything else
 * is the library's own. */
static int fail_mir(maelys_cli_context_t *context, maelys_mir_result_t result,
                    char *error, const char *what) {
  const char *code = result == MAELYS_MIR_ERR_MEMORY
                         ? MAELYS_CLI_CODE_UNEXPECTED
                         : MAELYS_CLI_CODE_VALIDATION_FAILED;
  int exit_code = maelys_cli_fail(context, code, NULL, "%s: %s: %s", what,
                                  maelys_mir_result_name(result),
                                  error ? error : "no diagnostic");
  maelys_mir_error_free(error);
  return exit_code;
}

static int succeed_digest(maelys_cli_context_t *context,
                          const char digest[MAELYS_MIR_DIGEST_HEX_SIZE]) {
  char human[MAELYS_MIR_DIGEST_HEX_SIZE + 8u];
  (void)snprintf(human, sizeof(human), "sha256:%s", digest);
  maelys_cli_json_writer_t data;
  maelys_cli_json_writer_init(&data);
  (void)maelys_cli_json_begin_object(&data);
  (void)maelys_cli_json_key_string(&data, "algorithm", "sha256");
  (void)maelys_cli_json_key_string(&data, "digest", digest);
  (void)maelys_cli_json_end_object(&data);
  return maelys_cli_succeed_writer(context, &data, human, MAELYS_CLI_EXIT_OK);
}

/* Reads and decodes canonical MIR, failing through the context. */
static int decode_policy(maelys_cli_context_t *context, const char *path,
                         maelys_mir_t **out) {
  unsigned char *bytes = NULL;
  size_t size = 0u;
  *out = NULL;
  if (read_input(context, path, &bytes, &size) != 0)
    return MAELYS_CLI_EXIT_FAILURE;
  char *error = NULL;
  maelys_mir_result_t result = maelys_mir_decode(bytes, size, out, &error);
  free(bytes);
  if (result != MAELYS_MIR_OK)
    return fail_mir(context, result, error, path);
  return MAELYS_CLI_EXIT_OK;
}

/* ---- compile (plan/apply transaction) ------------------------------------- */

static const maelys_cli_operand_t compile_operands[] = {
    {MAELYS_CLI_OPERAND("SOURCE", "Strict JSON policy source (format v3).")},
};
static const maelys_cli_option_t compile_options[] = {
    {MAELYS_CLI_PATH("output", "FILE", "Destination of the canonical MIR."),
     .required = 1},
    {MAELYS_CLI_FLAG("replace", "Allow replacing an existing output atomically.")},
    MAELYS_CLI_APPLY_OPTION,
};

static int command_compile(maelys_cli_context_t *context) {
  const char *source = maelys_cli_operand(context, 0u);
  const char *output = maelys_cli_option(context, "output");
  int replace = maelys_cli_flag(context, "replace");
  int apply = maelys_cli_flag(context, "apply");

  unsigned char *json = NULL;
  size_t json_size = 0u;
  if (read_input(context, source, &json, &json_size) != 0)
    return MAELYS_CLI_EXIT_FAILURE;
  maelys_mir_t *mir = NULL;
  char *error = NULL;
  maelys_mir_result_t result =
      maelys_mir_compile_json(json, json_size, &mir, &error);
  free(json);
  if (result != MAELYS_MIR_OK)
    return fail_mir(context, result, error, source);
  uint8_t *bytes = NULL;
  size_t size = 0u;
  char digest[MAELYS_MIR_DIGEST_HEX_SIZE];
  result = maelys_mir_encode(mir, &bytes, &size, &error);
  if (result == MAELYS_MIR_OK)
    result = maelys_mir_digest_hex(mir, digest, &error);
  maelys_mir_destroy(mir);
  if (result != MAELYS_MIR_OK) {
    maelys_mir_bytes_free(bytes);
    return fail_mir(context, result, error, source);
  }

  struct stat status;
  int absent = lstat(output, &status) != 0 && errno == ENOENT;
  if (!absent && !replace) {
    maelys_mir_bytes_free(bytes);
    return maelys_cli_fail(
        context, MAELYS_CLI_CODE_PRECONDITION_FAILED,
        "Choose a new path or add --replace to overwrite atomically.",
        "Output %s already exists.", output);
  }
  if (apply &&
      maelys_cli_write_file_atomic(output, bytes, size, 0644,
                                   replace ? MAELYS_CLI_WRITE_REPLACE
                                           : MAELYS_CLI_WRITE_NO_REPLACE) != 0) {
    int saved = errno;
    maelys_mir_bytes_free(bytes);
    return maelys_cli_fail_errno(context, MAELYS_CLI_CODE_IO_FAILED, saved,
                                 output);
  }
  maelys_mir_bytes_free(bytes);

  maelys_cli_json_writer_t data;
  maelys_cli_json_writer_init(&data);
  (void)maelys_cli_json_begin_object(&data);
  (void)maelys_cli_json_key_string(&data, "mode", apply ? "apply" : "plan");
  (void)maelys_cli_json_key_boolean(&data, "changed", apply);
  (void)maelys_cli_json_key_string(&data, "source", source);
  (void)maelys_cli_json_key_string(&data, "output", output);
  (void)maelys_cli_json_key_unsigned(&data, "bytes", (uint64_t)size);
  (void)maelys_cli_json_key_string(&data, "digest", digest);
  (void)maelys_cli_json_key(&data, "precondition");
  (void)maelys_cli_json_begin_object(&data);
  (void)maelys_cli_json_key_boolean(&data, "targetAbsent", absent);
  (void)maelys_cli_json_key_boolean(&data, "replace", replace);
  (void)maelys_cli_json_end_object(&data);
  (void)maelys_cli_json_end_object(&data);
  char human[512];
  (void)snprintf(human, sizeof(human),
                 apply ? "Wrote %s (%zu bytes, sha256:%s)."
                       : "Plan only; add --apply to write %s (%zu bytes, "
                         "sha256:%s).",
                 output, size, digest);
  return maelys_cli_succeed_writer(context, &data, human, MAELYS_CLI_EXIT_OK);
}

/* ---- validate (report, exit 2 on violation) -------------------------------- */

static const maelys_cli_operand_t policy_operands[] = {
    {MAELYS_CLI_OPERAND("POLICY", "Canonical MIR file.")},
};

static int command_validate(maelys_cli_context_t *context) {
  const char *path = maelys_cli_operand(context, 0u);
  unsigned char *bytes = NULL;
  size_t size = 0u;
  if (read_input(context, path, &bytes, &size) != 0)
    return MAELYS_CLI_EXIT_FAILURE;
  maelys_mir_t *mir = NULL;
  char *error = NULL;
  maelys_mir_result_t result = maelys_mir_decode(bytes, size, &mir, &error);
  free(bytes);
  char digest[MAELYS_MIR_DIGEST_HEX_SIZE] = "";
  if (result == MAELYS_MIR_OK)
    result = maelys_mir_digest_hex(mir, digest, &error);
  maelys_mir_destroy(mir);
  if (result == MAELYS_MIR_ERR_MEMORY)
    return fail_mir(context, result, error, path);
  int valid = result == MAELYS_MIR_OK;

  maelys_cli_json_writer_t data;
  maelys_cli_json_writer_init(&data);
  (void)maelys_cli_json_begin_object(&data);
  (void)maelys_cli_json_key_boolean(&data, "valid", valid);
  (void)maelys_cli_json_key_string(&data, "path", path);
  (void)maelys_cli_json_key_unsigned(&data, "formatVersion",
                                     MAELYS_MIR_FORMAT_VERSION);
  if (valid)
    (void)maelys_cli_json_key_string(&data, "digest", digest);
  (void)maelys_cli_json_key(&data, "diagnostics");
  (void)maelys_cli_json_begin_array(&data);
  char human[1024];
  if (valid) {
    (void)snprintf(human, sizeof(human), "valid MIR v%u",
                   MAELYS_MIR_FORMAT_VERSION);
  } else {
    char code[32] = "MIR_";
    const char *name = maelys_mir_result_name(result);
    for (size_t i = 0u; name[i] && i + 5u < sizeof(code); ++i)
      code[4u + i] = (char)(name[i] >= 'a' && name[i] <= 'z'
                                ? name[i] - 'a' + 'A'
                                : name[i]);
    const char *message = error ? error : "no diagnostic";
    (void)maelys_cli_json_begin_object(&data);
    (void)maelys_cli_json_key_string(&data, "code", code);
    (void)maelys_cli_json_key_string(&data, "message", message);
    (void)maelys_cli_json_end_object(&data);
    (void)snprintf(human, sizeof(human), "invalid MIR v%u: %s",
                   MAELYS_MIR_FORMAT_VERSION, message);
  }
  maelys_mir_error_free(error);
  (void)maelys_cli_json_end_array(&data);
  (void)maelys_cli_json_end_object(&data);
  return maelys_cli_succeed_writer(
      context, &data, human,
      valid ? MAELYS_CLI_EXIT_OK : MAELYS_CLI_EXIT_VIOLATIONS);
}

/* ---- hash, artifact-hash, inspect ------------------------------------------ */

static int command_hash(maelys_cli_context_t *context) {
  maelys_mir_t *mir = NULL;
  const char *path = maelys_cli_operand(context, 0u);
  if (decode_policy(context, path, &mir) != MAELYS_CLI_EXIT_OK)
    return MAELYS_CLI_EXIT_FAILURE;
  char digest[MAELYS_MIR_DIGEST_HEX_SIZE];
  char *error = NULL;
  maelys_mir_result_t result = maelys_mir_digest_hex(mir, digest, &error);
  maelys_mir_destroy(mir);
  if (result != MAELYS_MIR_OK)
    return fail_mir(context, result, error, path);
  return succeed_digest(context, digest);
}

static const maelys_cli_operand_t artifact_operands[] = {
    {MAELYS_CLI_OPERAND("FILE", "Any artifact, such as a policy source.")},
};

static int command_artifact_hash(maelys_cli_context_t *context) {
  const char *path = maelys_cli_operand(context, 0u);
  unsigned char *bytes = NULL;
  size_t size = 0u;
  if (read_input(context, path, &bytes, &size) != 0)
    return MAELYS_CLI_EXIT_FAILURE;
  char digest[MAELYS_MIR_DIGEST_HEX_SIZE];
  char *error = NULL;
  maelys_mir_result_t result =
      maelys_mir_artifact_digest_hex(bytes, size, digest, &error);
  free(bytes);
  if (result != MAELYS_MIR_OK)
    return fail_mir(context, result, error, path);
  return succeed_digest(context, digest);
}

static int command_inspect(maelys_cli_context_t *context) {
  maelys_mir_t *mir = NULL;
  const char *path = maelys_cli_operand(context, 0u);
  if (decode_policy(context, path, &mir) != MAELYS_CLI_EXIT_OK)
    return MAELYS_CLI_EXIT_FAILURE;
  uint8_t *json = NULL;
  size_t size = 0u;
  char *error = NULL;
  maelys_mir_result_t result = maelys_mir_inspect_json(mir, &json, &size, &error);
  maelys_mir_destroy(mir);
  if (result != MAELYS_MIR_OK)
    return fail_mir(context, result, error, path);
  /* The projection is its own deterministic text: it is the human form, and
   * as data it is validated and re-rendered like any other object. */
  char *text = malloc(size + 1u);
  if (!text) {
    maelys_mir_bytes_free(json);
    return maelys_cli_fail_errno(context, MAELYS_CLI_CODE_UNEXPECTED, ENOMEM,
                                 "inspection");
  }
  memcpy(text, json, size);
  text[size] = '\0';
  maelys_mir_bytes_free(json);
  if (size > 0u && text[size - 1u] == '\n')
    text[size - 1u] = '\0';
  int exit_code = maelys_cli_succeed(context, text, text, MAELYS_CLI_EXIT_OK);
  free(text);
  return exit_code;
}

/* ---- catalog ---------------------------------------------------------------- */

static const maelys_cli_command_t commands[] = {
    {MAELYS_CLI_TRANSACTION("compile", "compile",
                            "Compile a JSON policy source into canonical MIR.",
                            command_compile),
     MAELYS_CLI_OPERANDS(compile_operands), MAELYS_CLI_OPTIONS(compile_options),
     MAELYS_CLI_SCHEMA(policy_compile_schema)},
    {MAELYS_CLI_READ("validate", "validate",
                     "Check that a file is canonical MIR; exit 2 when it is not.",
                     command_validate),
     MAELYS_CLI_OPERANDS(policy_operands),
     MAELYS_CLI_SCHEMA(policy_validate_schema)},
    {MAELYS_CLI_READ("hash", "hash",
                     "Print the decision digest of canonical MIR.", command_hash),
     MAELYS_CLI_OPERANDS(policy_operands), MAELYS_CLI_SCHEMA(policy_hash_schema)},
    {MAELYS_CLI_READ("inspect", "inspect",
                     "Render the non-normative JSON projection of canonical MIR.",
                     command_inspect),
     MAELYS_CLI_OPERANDS(policy_operands),
     MAELYS_CLI_SCHEMA(policy_inspect_schema)},
    {MAELYS_CLI_READ("artifact-hash", "artifact-hash",
                     "Print the SHA-256 of any file; it carries no policy "
                     "identity.",
                     command_artifact_hash),
     MAELYS_CLI_OPERANDS(artifact_operands),
     MAELYS_CLI_SCHEMA(policy_hash_schema)},
};

int main(int argc, char **argv) {
  static const maelys_cli_app_t app = {
      .program = "maelys-policy",
      .product = "Maelys Sandbox Policy",
      .version = MAELYS_SANDBOX_POLICY_VERSION,
      .summary = "compile and verify canonical Maelys sandbox policies",
      .commands = commands,
      .command_count = MAELYS_CLI_COUNT(commands),
  };
  return maelys_cli_main(&app, argc, argv);
}
