/*
 * maelys-policy: the agent-cli/v2 command line of Maelys Sandbox Policy,
 * built on libmaelys_cli. It only reads and writes files; the policy work is
 * libmaelys-mir's.
 */
#include <maelys/cli.h>
#include <maelys/mir.h>
#include <maelys/sandbox_policy.h>

#include "policy_schemas.h" /* generated by maelys-cli-embed from cli/schemas/ */

#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>

/* ---- shared helpers ------------------------------------------------------- */

static int read_input(maelys_cli_context_t *context, const char *path,
                      unsigned char **out, size_t *out_size) {
  if (maelys_cli_read_regular_file(path, 0u, MAELYS_MIR_MAX_BYTES, out,
                                   out_size) == 0)
    return 0;
  int saved = errno;
  if (saved == EFBIG)
    return maelys_cli_fail(context, MAELYS_CLI_CODE_VALIDATION_FAILED,
                           "Policy inputs are limited to 1 MiB.",
                           "%s exceeds %u bytes.", path, MAELYS_MIR_MAX_BYTES);
  return maelys_cli_fail_file(context, saved, NULL, path);
}

/* A library failure the input caused is a validation failure; anything else
 * is the library's own. */
static int fail_mir(maelys_cli_context_t *context, maelys_mir_result_t result,
                    char *error, const char *what) {
  const char *code = result == MAELYS_MIR_ERR_MEMORY
                         ? MAELYS_CLI_CODE_UNEXPECTED
                         : MAELYS_CLI_CODE_VALIDATION_FAILED;
  int exit_code = maelys_cli_fail(context, code, NULL, "%s: %s: %s", what,
                                  maelys_mir_result_name(result),
                                  error ? error : "no diagnostic");
  maelys_mir_error_free(error);
  return exit_code;
}

static int succeed_digest(maelys_cli_context_t *context,
                          const char digest[MAELYS_MIR_DIGEST_HEX_SIZE]) {
  char human[MAELYS_MIR_DIGEST_HEX_SIZE + 8u];
  (void)snprintf(human, sizeof(human), "sha256:%s", digest);
  maelys_cli_json_writer_t data;
  maelys_cli_json_writer_init(&data);
  (void)maelys_cli_json_begin_object(&data);
  (void)maelys_cli_json_key_string(&data, "algorithm", "sha256");
  (void)maelys_cli_json_key_string(&data, "digest", digest);
  (void)maelys_cli_json_end_object(&data);
  return maelys_cli_succeed_writer(context, &data, human, MAELYS_CLI_EXIT_OK);
}

/* Reads and decodes canonical MIR, failing through the context. */
static int decode_policy(maelys_cli_context_t *context, const char *path,
                         maelys_mir_t **out) {
  unsigned char *bytes = NULL;
  size_t size = 0u;
  *out = NULL;
  if (read_input(context, path, &bytes, &size) != 0)
    return MAELYS_CLI_EXIT_FAILURE;
  char *error = NULL;
  maelys_mir_result_t result = maelys_mir_decode(bytes, size, out, &error);
  free(bytes);
  if (result != MAELYS_MIR_OK)
    return fail_mir(context, result, error, path);
  return MAELYS_CLI_EXIT_OK;
}

typedef struct published_policy {
  size_t size;
  char digest[MAELYS_MIR_DIGEST_HEX_SIZE];
  char fingerprint[MAELYS_CLI_FINGERPRINT_SIZE];
  int target_absent;
} published_policy_t;

/* The write half of a transaction that produces canonical MIR: encodes,
 * holds the output precondition and, under --apply, writes atomically. It
 * reads --output, --replace and --apply. On failure it has replied and
 * returns nonzero. */
static int publish_policy(maelys_cli_context_t *context, const maelys_mir_t *mir,
                          const char *action, const char *what,
                          published_policy_t *out) {
  const char *output = maelys_cli_option(context, "output");
  int replace = maelys_cli_flag(context, "replace");
  uint8_t *bytes = NULL;
  char *error = NULL;
  maelys_mir_result_t result = maelys_mir_encode(mir, &bytes, &out->size, &error);
  if (result == MAELYS_MIR_OK)
    result = maelys_mir_digest_hex(mir, out->digest, &error);
  if (result != MAELYS_MIR_OK) {
    maelys_mir_bytes_free(bytes);
    (void)fail_mir(context, result, error, what);
    return 1;
  }
  struct stat status;
  out->target_absent = lstat(output, &status) != 0 && errno == ENOENT;
  if (!out->target_absent && !replace) {
    maelys_mir_bytes_free(bytes);
    (void)maelys_cli_fail(
        context, MAELYS_CLI_CODE_PRECONDITION_FAILED,
        "Choose a new path or add --replace to overwrite atomically.",
        "Output %s already exists.", output);
    return 1;
  }
  /* The fingerprint of the plan: the action (which command, which inputs by
   * name, which output, replacing or not), what it would write (the digest
   * is the identity of the policy, so the same bytes), and what is at the
   * output now. Under --apply --expect, another plan, or the same plan over
   * an output that changed since it was read, is refused before the write. */
  maelys_cli_fingerprint_t plan;
  maelys_cli_fingerprint_init(&plan);
  maelys_cli_fingerprint_add_string(&plan, "action", action);
  for (size_t i = 0; i < maelys_cli_operand_count(context); ++i)
    maelys_cli_fingerprint_add_string(&plan, "input",
                                      maelys_cli_operand(context, i));
  maelys_cli_fingerprint_add_string(&plan, "output", output);
  maelys_cli_fingerprint_add_string(&plan, "replace", replace ? "true" : "false");
  maelys_cli_fingerprint_add_string(&plan, "digest", out->digest);
  if (maelys_cli_fingerprint_add_file(&plan, "target", output,
                                      MAELYS_MIR_MAX_BYTES) != 0) {
    int saved = errno;
    maelys_mir_bytes_free(bytes);
    (void)maelys_cli_fail_errno(context, MAELYS_CLI_CODE_IO_FAILED, saved,
                                output);
    return 1;
  }
  maelys_cli_fingerprint_finish(&plan, out->fingerprint);
  int refused = maelys_cli_expect(context, out->fingerprint);
  if (refused) {
    maelys_mir_bytes_free(bytes);
    return refused;
  }
  if (maelys_cli_flag(context, "apply") &&
      maelys_cli_write_file_atomic(output, bytes, out->size, 0644,
                                   replace ? MAELYS_CLI_WRITE_REPLACE
                                           : MAELYS_CLI_WRITE_NO_REPLACE) != 0) {
    int saved = errno;
    maelys_mir_bytes_free(bytes);
    (void)maelys_cli_fail_errno(context, MAELYS_CLI_CODE_IO_FAILED, saved,
                                output);
    return 1;
  }
  maelys_mir_bytes_free(bytes);
  return 0;
}

static void write_publication(maelys_cli_json_writer_t *data,
                              maelys_cli_context_t *context,
                              const published_policy_t *published) {
  (void)maelys_cli_json_key_string(data, "output",
                                   maelys_cli_option(context, "output"));
  (void)maelys_cli_json_key_unsigned(data, "bytes", (uint64_t)published->size);
  (void)maelys_cli_json_key_string(data, "digest", published->digest);
  (void)maelys_cli_json_key_string(data, "fingerprint", published->fingerprint);
  (void)maelys_cli_json_key(data, "precondition");
  (void)maelys_cli_json_begin_object(data);
  (void)maelys_cli_json_key_boolean(data, "targetAbsent",
                                    published->target_absent);
  (void)maelys_cli_json_key_boolean(data, "replace",
                                    maelys_cli_flag(context, "replace"));
  (void)maelys_cli_json_end_object(data);
}

static void describe_publication(maelys_cli_context_t *context,
                                 const published_policy_t *published,
                                 char *human, size_t size) {
  (void)snprintf(human, size,
                 maelys_cli_flag(context, "apply")
                     ? "Wrote %s (%zu bytes, sha256:%s)."
                     : "Plan only; add --apply to write %s (%zu bytes, "
                       "sha256:%s).",
                 maelys_cli_option(context, "output"), published->size,
                 published->digest);
}

/* ---- compile (plan/apply transaction) ------------------------------------- */

static const maelys_cli_operand_t compile_operands[] = {
    {MAELYS_CLI_OPERAND("SOURCE", "Strict JSON policy source (format v3).")},
};
/* The options of every transaction that writes canonical MIR. */
static const maelys_cli_option_t publish_options[] = {
    {MAELYS_CLI_PATH("output", "FILE", "Destination of the canonical MIR."),
     .required = 1},
    {MAELYS_CLI_FLAG("replace", "Allow replacing an existing output atomically.")},
    MAELYS_CLI_APPLY_OPTION,
    MAELYS_CLI_EXPECT_OPTION,
};

static int command_compile(maelys_cli_context_t *context) {
  const char *source = maelys_cli_operand(context, 0u);
  int apply = maelys_cli_flag(context, "apply");
  unsigned char *json = NULL;
  size_t json_size = 0u;
  if (read_input(context, source, &json, &json_size) != 0)
    return MAELYS_CLI_EXIT_FAILURE;
  maelys_mir_t *mir = NULL;
  char *error = NULL;
  maelys_mir_result_t result =
      maelys_mir_compile_json(json, json_size, &mir, &error);
  free(json);
  if (result != MAELYS_MIR_OK)
    return fail_mir(context, result, error, source);
  published_policy_t published;
  int failed = publish_policy(context, mir, "compile", source, &published);
  maelys_mir_destroy(mir);
  if (failed)
    return MAELYS_CLI_EXIT_FAILURE;

  maelys_cli_json_writer_t data;
  maelys_cli_json_writer_init(&data);
  (void)maelys_cli_json_begin_object(&data);
  (void)maelys_cli_json_key_string(&data, "mode", apply ? "apply" : "plan");
  (void)maelys_cli_json_key_boolean(&data, "changed", apply);
  (void)maelys_cli_json_key_string(&data, "source", source);
  write_publication(&data, context, &published);
  (void)maelys_cli_json_end_object(&data);
  char human[512];
  describe_publication(context, &published, human, sizeof(human));
  return maelys_cli_succeed_writer(context, &data, human, MAELYS_CLI_EXIT_OK);
}

/* ---- restrict (plan/apply transaction) ------------------------------------- */

static const maelys_cli_operand_t restrict_operands[] = {
    {MAELYS_CLI_OPERAND("BASE", "Canonical MIR of the trusted base policy.")},
    {MAELYS_CLI_OPERAND("RESTRICTION",
                        "Canonical MIR of the ceiling to apply: filesystem "
                        "deny rules only.")},
};

static int command_restrict(maelys_cli_context_t *context) {
  const char *base_path = maelys_cli_operand(context, 0u);
  const char *restriction_path = maelys_cli_operand(context, 1u);
  int apply = maelys_cli_flag(context, "apply");
  maelys_mir_t *base = NULL, *restriction = NULL, *effective = NULL;
  if (decode_policy(context, base_path, &base) != MAELYS_CLI_EXIT_OK)
    return MAELYS_CLI_EXIT_FAILURE;
  if (decode_policy(context, restriction_path, &restriction) !=
      MAELYS_CLI_EXIT_OK) {
    maelys_mir_destroy(base);
    return MAELYS_CLI_EXIT_FAILURE;
  }
  char base_digest[MAELYS_MIR_DIGEST_HEX_SIZE];
  char restriction_digest[MAELYS_MIR_DIGEST_HEX_SIZE];
  char *error = NULL;
  maelys_mir_result_t result = maelys_mir_digest_hex(base, base_digest, &error);
  if (result == MAELYS_MIR_OK)
    result = maelys_mir_digest_hex(restriction, restriction_digest, &error);
  if (result == MAELYS_MIR_OK)
    result = maelys_mir_restrict(base, restriction, &effective, &error);
  maelys_mir_destroy(base);
  maelys_mir_destroy(restriction);
  if (result != MAELYS_MIR_OK)
    return fail_mir(context, result, error, restriction_path);
  published_policy_t published;
  int failed =
      publish_policy(context, effective, "restrict", restriction_path, &published);
  maelys_mir_destroy(effective);
  if (failed)
    return MAELYS_CLI_EXIT_FAILURE;

  maelys_cli_json_writer_t data;
  maelys_cli_json_writer_init(&data);
  (void)maelys_cli_json_begin_object(&data);
  (void)maelys_cli_json_key_string(&data, "mode", apply ? "apply" : "plan");
  (void)maelys_cli_json_key_boolean(&data, "changed", apply);
  (void)maelys_cli_json_key_string(&data, "base", base_path);
  (void)maelys_cli_json_key_string(&data, "baseDigest", base_digest);
  (void)maelys_cli_json_key_string(&data, "restriction", restriction_path);
  (void)maelys_cli_json_key_string(&data, "restrictionDigest",
                                   restriction_digest);
  write_publication(&data, context, &published);
  (void)maelys_cli_json_end_object(&data);
  char human[512];
  describe_publication(context, &published, human, sizeof(human));
  return maelys_cli_succeed_writer(context, &data, human, MAELYS_CLI_EXIT_OK);
}

/* ---- capabilities (report, exit 2 when a check finds some missing) --------- */

/* One name per capability bit, in bit order: the identifiers of
 * maelys_sandbox_policy_capability_name(), which the handler maps back. */
static const char *const capability_choices[] = {
    "fs-read",          "fs-write",           "fs-deny",
    "network-none",     "network-direct",     "network-mediated",
    "process-tree",     "root-ephemeral-write", "network-require-tls-sni",
    "network-private-addresses", "fs-protect-create", "fs-deny-write", NULL};

#define CAPABILITY_CHECK_OPTIONS                                                \
  {MAELYS_CLI_FLAG("check",                                                     \
                   "Compare the requirements with the capabilities given "     \
                   "by --available, none if it is absent; exit 2 when "        \
                   "some are missing.")},                                       \
  {MAELYS_CLI_CHOICE("available",                                               \
                     "Capability a backend is declared to offer; repeatable.", \
                     capability_choices),                                       \
   .value_name = "CAPABILITY", .repeatable = 1, .depends_on = "check"}

static const maelys_cli_option_t capabilities_options[] = {
    CAPABILITY_CHECK_OPTIONS,
};

/* The set --available declares. On failure it has replied and returns
 * nonzero. */
static int declared_capabilities(maelys_cli_context_t *context,
                                 maelys_sandbox_policy_capabilities_t *out) {
  *out = 0;
  size_t given = maelys_cli_option_count(context, "available");
  for (size_t i = 0u; i < given; ++i) {
    const char *name = maelys_cli_option_at(context, "available", i);
    maelys_sandbox_policy_capabilities_t bit = 0;
    for (unsigned b = 0; b < 64u && !bit; ++b) {
      const char *known =
          maelys_sandbox_policy_capability_name(UINT64_C(1) << b);
      if (known && strcmp(known, name) == 0)
        bit = UINT64_C(1) << b;
    }
    if (!bit) {
      (void)maelys_cli_fail(context, MAELYS_CLI_CODE_UNEXPECTED, NULL,
                            "The catalog offers %s, which the library does "
                            "not name.",
                            name);
      return 1;
    }
    *out |= bit;
  }
  return 0;
}

static void write_capabilities(maelys_cli_json_writer_t *data, const char *key,
                               maelys_sandbox_policy_capabilities_t set) {
  (void)maelys_cli_json_key(data, key);
  (void)maelys_cli_json_begin_array(data);
  for (unsigned bit = 0; bit < 64u; ++bit) {
    const char *name =
        maelys_sandbox_policy_capability_name(UINT64_C(1) << bit);
    if (name && (set & (UINT64_C(1) << bit)))
      (void)maelys_cli_json_string(data, name);
  }
  (void)maelys_cli_json_end_array(data);
}

static size_t list_capabilities(maelys_sandbox_policy_capabilities_t set,
                                char *out, size_t size) {
  size_t used = 0u;
  out[0] = '\0';
  for (unsigned bit = 0; bit < 64u; ++bit) {
    const char *name =
        maelys_sandbox_policy_capability_name(UINT64_C(1) << bit);
    if (!name || !(set & (UINT64_C(1) << bit)))
      continue;
    int written = snprintf(out + used, size - used, "%s%s", used ? ", " : "",
                           name);
    if (written < 0 || (size_t)written >= size - used)
      break;
    used += (size_t)written;
  }
  if (!used)
    (void)snprintf(out, size, "none");
  return used;
}

static int command_capabilities(maelys_cli_context_t *context) {
  const char *path = maelys_cli_operand(context, 0u);
  int check = maelys_cli_flag(context, "check");
  maelys_sandbox_policy_capabilities_t available = 0;
  if (declared_capabilities(context, &available))
    return MAELYS_CLI_EXIT_FAILURE;
  maelys_mir_t *mir = NULL;
  if (decode_policy(context, path, &mir) != MAELYS_CLI_EXIT_OK)
    return MAELYS_CLI_EXIT_FAILURE;
  char digest[MAELYS_MIR_DIGEST_HEX_SIZE];
  char *error = NULL;
  maelys_mir_result_t result = maelys_mir_digest_hex(mir, digest, &error);
  if (result != MAELYS_MIR_OK) {
    maelys_mir_destroy(mir);
    return fail_mir(context, result, error, path);
  }
  maelys_sandbox_policy_capabilities_t required =
      maelys_sandbox_policy_required_capabilities(mir);
  /* What only resolution on a host can settle. A deny or deny-write with
   * missing:skip needs fs-protect-create exactly where its target is
   * absent. */
  maelys_sandbox_policy_capabilities_t resolution = 0;
  for (size_t i = 0u; i < maelys_mir_fs_rule_count(mir); ++i) {
    maelys_mir_fs_rule_view_t rule;
    if (maelys_mir_fs_rule_at(mir, i, &rule) == MAELYS_MIR_OK &&
        (rule.access == MAELYS_MIR_FS_DENY ||
         rule.access == MAELYS_MIR_FS_DENY_WRITE) &&
        rule.missing == MAELYS_MIR_MISSING_SKIP)
      resolution |= MAELYS_SANDBOX_POLICY_CAP_FS_PROTECT_CREATE;
  }
  maelys_mir_destroy(mir);
  maelys_sandbox_policy_capabilities_t missing = required & ~available;

  maelys_cli_json_writer_t data;
  maelys_cli_json_writer_init(&data);
  (void)maelys_cli_json_begin_object(&data);
  (void)maelys_cli_json_key_string(&data, "policy", path);
  (void)maelys_cli_json_key_string(&data, "digest", digest);
  (void)maelys_cli_json_key_string(&data, "scope", "mir");
  write_capabilities(&data, "required", required);
  write_capabilities(&data, "resolutionMayRequire", resolution & ~required);
  (void)maelys_cli_json_key_boolean(&data, "checked", check);
  if (check) {
    write_capabilities(&data, "available", available);
    write_capabilities(&data, "missing", missing);
    (void)maelys_cli_json_key_boolean(&data, "supported", missing == 0);
  }
  (void)maelys_cli_json_end_object(&data);

  char names[512], later[128], lacking[512], human[1400];
  (void)list_capabilities(required, names, sizeof(names));
  (void)list_capabilities(resolution & ~required, later, sizeof(later));
  (void)list_capabilities(missing, lacking, sizeof(lacking));
  int used = snprintf(human, sizeof(human),
                      "requires: %s\nresolution may require: %s", names, later);
  if (check && used > 0 && (size_t)used < sizeof(human))
    (void)snprintf(human + used, sizeof(human) - (size_t)used, "\nmissing: %s",
                   lacking);
  return maelys_cli_succeed_writer(
      context, &data, human,
      check && missing ? MAELYS_CLI_EXIT_VIOLATIONS : MAELYS_CLI_EXIT_OK);
}

/* ---- resolution on a host: shared by resolve and evaluate ------------------ */

#define HOST_CONTEXT_OPTIONS                                                    \
  {MAELYS_CLI_ABSOLUTE_PATH("workspace", "DIR",                                 \
                            "Host directory the workspace root stands for.")}, \
  {MAELYS_CLI_ABSOLUTE_PATH("temp", "DIR",                                      \
                            "Host directory the temp root stands for.")},      \
  {MAELYS_CLI_ABSOLUTE_PATH("minimal-root", "DIR",                              \
                            "Host directory of the minimal runtime; "          \
                            "repeatable."),                                     \
   .repeatable = 1},                                                            \
  {MAELYS_CLI_STRING("mediator", "ID",                                          \
                     "Trusted network mediator, for a mediated policy.")}

/* The trusted host context the options describe. On failure it has replied
 * and returns NULL. Every command that resolves builds it before it reads a
 * policy file, so an invalid option is reported before an invalid operand
 * file whatever the command. */
static maelys_sandbox_policy_host_t *host_context(maelys_cli_context_t *context) {
  maelys_sandbox_policy_host_t *host = NULL;
  char *error = NULL;
  const char *option = "host context";
  maelys_mir_result_t result = maelys_sandbox_policy_host_create(&host, &error);
  if (result == MAELYS_MIR_OK && maelys_cli_option(context, "workspace")) {
    option = "--workspace";
    result = maelys_sandbox_policy_host_set_workspace(
        host, maelys_cli_option(context, "workspace"), &error);
  }
  if (result == MAELYS_MIR_OK && maelys_cli_option(context, "temp")) {
    option = "--temp";
    result = maelys_sandbox_policy_host_set_temp(
        host, maelys_cli_option(context, "temp"), &error);
  }
  size_t roots = maelys_cli_option_count(context, "minimal-root");
  for (size_t i = 0u; result == MAELYS_MIR_OK && i < roots; ++i) {
    option = "--minimal-root";
    result = maelys_sandbox_policy_host_add_minimal_runtime_root(
        host, maelys_cli_option_at(context, "minimal-root", i), &error);
  }
  if (result == MAELYS_MIR_OK && maelys_cli_option(context, "mediator")) {
    option = "--mediator";
    result = maelys_sandbox_policy_host_set_network_mediator(
        host, maelys_cli_option(context, "mediator"), &error);
  }
  if (result == MAELYS_MIR_OK)
    return host;
  maelys_sandbox_policy_host_destroy(host);
  (void)maelys_cli_fail(context,
                        result == MAELYS_MIR_ERR_MEMORY
                            ? MAELYS_CLI_CODE_UNEXPECTED
                            : MAELYS_CLI_CODE_VALIDATION_FAILED,
                        "Name an existing directory of this host.",
                        "%s: %s: %s", option, maelys_mir_result_name(result),
                        error ? error : "no diagnostic");
  maelys_mir_error_free(error);
  return NULL;
}

static void write_context(maelys_cli_json_writer_t *data,
                          maelys_cli_context_t *context) {
  (void)maelys_cli_json_key(data, "context");
  (void)maelys_cli_json_begin_object(data);
  if (maelys_cli_option(context, "workspace"))
    (void)maelys_cli_json_key_string(data, "workspace",
                                     maelys_cli_option(context, "workspace"));
  if (maelys_cli_option(context, "temp"))
    (void)maelys_cli_json_key_string(data, "temp",
                                     maelys_cli_option(context, "temp"));
  (void)maelys_cli_json_key(data, "minimalRoots");
  (void)maelys_cli_json_begin_array(data);
  size_t roots = maelys_cli_option_count(context, "minimal-root");
  for (size_t i = 0u; i < roots; ++i)
    (void)maelys_cli_json_string(
        data, maelys_cli_option_at(context, "minimal-root", i));
  (void)maelys_cli_json_end_array(data);
  if (maelys_cli_option(context, "mediator"))
    (void)maelys_cli_json_key_string(data, "mediator",
                                     maelys_cli_option(context, "mediator"));
  (void)maelys_cli_json_end_object(data);
}

static const char *fs_access_name(maelys_mir_fs_access_t access) {
  return access == MAELYS_MIR_FS_READ         ? "read"
         : access == MAELYS_MIR_FS_WRITE      ? "write"
         : access == MAELYS_MIR_FS_DENY_WRITE ? "deny-write"
                                              : "deny";
}

static const char *fs_scope_name(maelys_mir_path_scope_t scope) {
  return scope == MAELYS_MIR_SCOPE_TREE ? "tree" : "exact";
}

static void write_resolved_rule(
    maelys_cli_json_writer_t *data,
    const maelys_sandbox_policy_resolved_rule_view_t *rule) {
  (void)maelys_cli_json_begin_object(data);
  (void)maelys_cli_json_key_string(data, "access", fs_access_name(rule->access));
  (void)maelys_cli_json_key_string(data, "scope", fs_scope_name(rule->scope));
  (void)maelys_cli_json_key_string(data, "path", rule->path);
  (void)maelys_cli_json_key_string(
      data, "missing",
      rule->missing == MAELYS_SANDBOX_POLICY_MISSING_PROTECT_CREATE
          ? "protect-create"
          : "error");
  (void)maelys_cli_json_end_object(data);
}

/* MIR_<RESULT>, the code a report gives a refusal of the library. */
static void result_code(maelys_mir_result_t result, char *out, size_t size) {
  const char *name = maelys_mir_result_name(result);
  size_t used = (size_t)snprintf(out, size, "MIR_");
  for (size_t i = 0u; name[i] && used + 1u < size; ++i, ++used)
    out[used] = (char)(name[i] >= 'a' && name[i] <= 'z' ? name[i] - 'a' + 'A'
                                                         : name[i]);
  out[used] = '\0';
}

/* ---- resolve (report, exit 2 when something prevents the execution) -------- */

static const maelys_cli_option_t resolve_options[] = {
    HOST_CONTEXT_OPTIONS,
    CAPABILITY_CHECK_OPTIONS,
};

static int command_resolve(maelys_cli_context_t *context) {
  const char *path = maelys_cli_operand(context, 0u);
  int check = maelys_cli_flag(context, "check");
  maelys_sandbox_policy_capabilities_t available = 0;
  if (declared_capabilities(context, &available))
    return MAELYS_CLI_EXIT_FAILURE;
  maelys_sandbox_policy_host_t *host = host_context(context);
  if (!host)
    return MAELYS_CLI_EXIT_FAILURE;
  maelys_mir_t *mir = NULL;
  if (decode_policy(context, path, &mir) != MAELYS_CLI_EXIT_OK) {
    maelys_sandbox_policy_host_destroy(host);
    return MAELYS_CLI_EXIT_FAILURE;
  }
  char digest[MAELYS_MIR_DIGEST_HEX_SIZE];
  char *error = NULL;
  maelys_mir_result_t result = maelys_mir_digest_hex(mir, digest, &error);
  if (result != MAELYS_MIR_OK) {
    maelys_sandbox_policy_host_destroy(host);
    maelys_mir_destroy(mir);
    return fail_mir(context, result, error, path);
  }
  /* Resolve as if the backend offered everything: the report states what
   * the policy needs here, and judges a declared backend apart. */
  maelys_sandbox_policy_plan_t *plan = NULL;
  result = maelys_sandbox_policy_compile(mir, host, UINT64_MAX, &plan, &error);
  maelys_sandbox_policy_host_destroy(host);
  if (result == MAELYS_MIR_ERR_MEMORY) {
    maelys_mir_destroy(mir);
    return fail_mir(context, result, error, path);
  }
  maelys_sandbox_policy_capabilities_t required =
      plan ? maelys_sandbox_policy_plan_required_capabilities(plan)
           : maelys_sandbox_policy_required_capabilities(mir);
  maelys_sandbox_policy_capabilities_t missing = required & ~available;
  maelys_mir_destroy(mir);
  int blocked = !plan || (check && missing);

  maelys_cli_json_writer_t data;
  maelys_cli_json_writer_init(&data);
  (void)maelys_cli_json_begin_object(&data);
  (void)maelys_cli_json_key_string(&data, "policy", path);
  (void)maelys_cli_json_key_string(&data, "digest", digest);
  (void)maelys_cli_json_key_string(&data, "scope", "host");
  (void)maelys_cli_json_key_unsigned(&data, "permissionContract",
                                     MAELYS_SANDBOX_POLICY_PERMISSION_CONTRACT);
  write_context(&data, context);
  (void)maelys_cli_json_key_boolean(&data, "resolved", plan != NULL);
  (void)maelys_cli_json_key(&data, "rules");
  (void)maelys_cli_json_begin_array(&data);
  for (size_t i = 0u; i < maelys_sandbox_policy_plan_rule_count(plan); ++i) {
    maelys_sandbox_policy_resolved_rule_view_t rule;
    if (maelys_sandbox_policy_plan_rule_at(plan, i, &rule) == MAELYS_MIR_OK)
      write_resolved_rule(&data, &rule);
  }
  (void)maelys_cli_json_end_array(&data);
  (void)maelys_cli_json_key(&data, "omitted");
  (void)maelys_cli_json_begin_array(&data);
  for (size_t i = 0u; i < maelys_sandbox_policy_plan_omitted_rule_count(plan);
       ++i) {
    static const char *const roots[] = {"", "minimal-runtime", "workspace",
                                        "temp", "host"};
    maelys_sandbox_policy_omitted_rule_view_t rule;
    if (maelys_sandbox_policy_plan_omitted_rule_at(plan, i, &rule) !=
        MAELYS_MIR_OK)
      continue;
    (void)maelys_cli_json_begin_object(&data);
    (void)maelys_cli_json_key_string(&data, "access",
                                     fs_access_name(rule.access));
    (void)maelys_cli_json_key_string(&data, "scope", fs_scope_name(rule.scope));
    (void)maelys_cli_json_key_string(&data, "root", roots[rule.root]);
    (void)maelys_cli_json_key_string(&data, "relative", rule.relative);
    if (rule.host_root)
      (void)maelys_cli_json_key_string(&data, "hostRoot", rule.host_root);
    (void)maelys_cli_json_key_string(&data, "reason", "absent-grant");
    (void)maelys_cli_json_end_object(&data);
  }
  (void)maelys_cli_json_end_array(&data);
  (void)maelys_cli_json_key(&data, "capabilities");
  (void)maelys_cli_json_begin_object(&data);
  /* Without a plan only the MIR speaks: resolution may have asked more. */
  (void)maelys_cli_json_key_string(&data, "from", plan ? "plan" : "mir");
  write_capabilities(&data, "required", required);
  (void)maelys_cli_json_key_boolean(&data, "checked", check);
  if (check) {
    write_capabilities(&data, "available", available);
    write_capabilities(&data, "missing", missing);
    (void)maelys_cli_json_key_boolean(&data, "supported", missing == 0);
  }
  (void)maelys_cli_json_end_object(&data);
  (void)maelys_cli_json_key(&data, "blockers");
  (void)maelys_cli_json_begin_array(&data);
  if (!plan) {
    char code[32];
    result_code(result, code, sizeof(code));
    (void)maelys_cli_json_begin_object(&data);
    (void)maelys_cli_json_key_string(&data, "code", code);
    (void)maelys_cli_json_key_string(&data, "message",
                                     error ? error : "no diagnostic");
    (void)maelys_cli_json_end_object(&data);
  }
  if (check && missing) {
    char names[512], message[600];
    (void)list_capabilities(missing, names, sizeof(names));
    (void)snprintf(message, sizeof(message),
                   "the declared backend lacks: %s", names);
    (void)maelys_cli_json_begin_object(&data);
    (void)maelys_cli_json_key_string(&data, "code", "CAPABILITIES_MISSING");
    (void)maelys_cli_json_key_string(&data, "message", message);
    (void)maelys_cli_json_end_object(&data);
  }
  (void)maelys_cli_json_end_array(&data);
  (void)maelys_cli_json_key_boolean(&data, "blocked", blocked);
  (void)maelys_cli_json_end_object(&data);
  maelys_mir_error_free(error);
  maelys_sandbox_policy_plan_destroy(plan);
  return maelys_cli_succeed_writer(
      context, &data, NULL,
      blocked ? MAELYS_CLI_EXIT_VIOLATIONS : MAELYS_CLI_EXIT_OK);
}

/* Decodes one policy and resolves it on the host. On failure it has replied
 * and returns nonzero: without a plan there is nothing to compare. */
static int resolve_operand(maelys_cli_context_t *context,
                           const maelys_sandbox_policy_host_t *host,
                           const char *path,
                           char digest[MAELYS_MIR_DIGEST_HEX_SIZE],
                           maelys_sandbox_policy_plan_t **out) {
  maelys_mir_t *mir = NULL;
  *out = NULL;
  if (decode_policy(context, path, &mir) != MAELYS_CLI_EXIT_OK)
    return 1;
  char *error = NULL;
  maelys_mir_result_t result = maelys_mir_digest_hex(mir, digest, &error);
  if (result != MAELYS_MIR_OK) {
    maelys_mir_destroy(mir);
    (void)fail_mir(context, result, error, path);
    return 1;
  }
  result = maelys_sandbox_policy_compile(mir, host, UINT64_MAX, out, &error);
  maelys_mir_destroy(mir);
  if (result == MAELYS_MIR_OK)
    return 0;
  (void)maelys_cli_fail(
      context,
      result == MAELYS_MIR_ERR_MEMORY     ? MAELYS_CLI_CODE_UNEXPECTED
      : result == MAELYS_MIR_ERR_CONFLICT ? MAELYS_CLI_CODE_POLICY_FAILED
                                          : MAELYS_CLI_CODE_PRECONDITION_FAILED,
      "Run 'maelys-policy resolve' with the same context for the report.",
      "%s does not resolve on this host: %s: %s", path,
      maelys_mir_result_name(result), error ? error : "no diagnostic");
  maelys_mir_error_free(error);
  return 1;
}

/* ---- evaluate (what the resolved plan grants on one path) ------------------ */

static const maelys_cli_option_t evaluate_options[] = {
    {MAELYS_CLI_ABSOLUTE_PATH("path", "PATH",
                              "Resolved absolute path to evaluate, taken as "
                              "written: no link is followed."),
     .required = 1},
    HOST_CONTEXT_OPTIONS,
};

static int command_evaluate(maelys_cli_context_t *context) {
  const char *path = maelys_cli_operand(context, 0u);
  const char *target = maelys_cli_option(context, "path");
  maelys_sandbox_policy_host_t *host = host_context(context);
  if (!host)
    return MAELYS_CLI_EXIT_FAILURE;
  char digest[MAELYS_MIR_DIGEST_HEX_SIZE];
  maelys_sandbox_policy_plan_t *plan = NULL;
  /* No plan, no answer: a policy that does not resolve grants nothing that
   * could be evaluated. resolve reports why. */
  int failed = resolve_operand(context, host, path, digest, &plan);
  maelys_sandbox_policy_host_destroy(host);
  if (failed)
    return MAELYS_CLI_EXIT_FAILURE;
  char *error = NULL;
  maelys_sandbox_policy_evaluation_t evaluation;
  maelys_mir_result_t result =
      maelys_sandbox_policy_plan_evaluate(plan, target, &evaluation, &error);
  if (result != MAELYS_MIR_OK) {
    maelys_sandbox_policy_plan_destroy(plan);
    int exit_code = maelys_cli_fail(
        context, MAELYS_CLI_CODE_VALIDATION_FAILED,
        "Give the path as the plan names paths: absolute and canonical.",
        "--path %s: %s", target, error ? error : "no diagnostic");
    maelys_mir_error_free(error);
    return exit_code;
  }
  const char *permission =
      maelys_sandbox_policy_permission_name(evaluation.permission);
  const char *reason = maelys_sandbox_policy_reason_name(evaluation.reason);
  maelys_sandbox_policy_resolved_rule_view_t rule;
  int decided = evaluation.decisive_rule != SIZE_MAX &&
                maelys_sandbox_policy_plan_rule_at(plan, evaluation.decisive_rule,
                                                   &rule) == MAELYS_MIR_OK;

  maelys_cli_json_writer_t data;
  maelys_cli_json_writer_init(&data);
  (void)maelys_cli_json_begin_object(&data);
  (void)maelys_cli_json_key_string(&data, "policy", path);
  (void)maelys_cli_json_key_string(&data, "digest", digest);
  (void)maelys_cli_json_key_string(&data, "scope", "host");
  (void)maelys_cli_json_key_unsigned(&data, "permissionContract",
                                     MAELYS_SANDBOX_POLICY_PERMISSION_CONTRACT);
  write_context(&data, context);
  (void)maelys_cli_json_key_string(&data, "path", target);
  (void)maelys_cli_json_key_string(&data, "permission", permission);
  (void)maelys_cli_json_key_string(&data, "reason", reason);
  (void)maelys_cli_json_key_unsigned(&data, "applicableRules",
                                     (uint64_t)evaluation.applicable_rule_count);
  if (decided) {
    (void)maelys_cli_json_key(&data, "decisiveRule");
    write_resolved_rule(&data, &rule);
  }
  (void)maelys_cli_json_end_object(&data);
  char human[4400];
  if (decided)
    (void)snprintf(human, sizeof(human), "%s (%s): %s %s %s", permission, reason,
                   fs_access_name(rule.access), fs_scope_name(rule.scope),
                   rule.path);
  else
    (void)snprintf(human, sizeof(human), "%s (%s)", permission, reason);
  int exit_code =
      maelys_cli_succeed_writer(context, &data, human, MAELYS_CLI_EXIT_OK);
  maelys_sandbox_policy_plan_destroy(plan);
  return exit_code;
}

/* ---- contains (report, exit 2 when the candidate exceeds the boundary) ----- */

static const maelys_cli_operand_t contains_operands[] = {
    {MAELYS_CLI_OPERAND("BOUNDARY", "Canonical MIR of the ceiling.")},
    {MAELYS_CLI_OPERAND("CANDIDATE",
                        "Canonical MIR that must grant nothing more.")},
};
static const maelys_cli_option_t contains_options[] = {
    HOST_CONTEXT_OPTIONS,
};

static const char *network_mode_name(maelys_mir_network_mode_t mode) {
  return mode == MAELYS_MIR_NETWORK_NONE       ? "none"
         : mode == MAELYS_MIR_NETWORK_MEDIATED ? "mediated"
                                               : "direct";
}

static void write_decisive_rule(maelys_cli_json_writer_t *data, const char *key,
                                const maelys_sandbox_policy_plan_t *plan,
                                size_t index) {
  maelys_sandbox_policy_resolved_rule_view_t rule;
  if (index == SIZE_MAX ||
      maelys_sandbox_policy_plan_rule_at(plan, index, &rule) != MAELYS_MIR_OK)
    return;
  (void)maelys_cli_json_key(data, key);
  write_resolved_rule(data, &rule);
}

/* What a comparison looked at. Anything outside this list was not compared,
 * and no verdict covers it. */
static void write_analysed(maelys_cli_json_writer_t *data, int constraints) {
  (void)maelys_cli_json_key(data, "analysed");
  (void)maelys_cli_json_begin_array(data);
  (void)maelys_cli_json_string(data, "filesystem");
  (void)maelys_cli_json_string(data, "network");
  if (constraints) {
    (void)maelys_cli_json_string(data, "root");
    (void)maelys_cli_json_string(data, "process");
  }
  (void)maelys_cli_json_end_array(data);
}

static void write_destination(maelys_cli_json_writer_t *data,
                              const maelys_sandbox_policy_plan_t *plan,
                              size_t index) {
  maelys_mir_network_destination_ex_view_t d;
  if (maelys_sandbox_policy_plan_network_destination_at_ex(plan, index, &d) !=
      MAELYS_MIR_OK)
    return;
  (void)maelys_cli_json_begin_object(data);
  (void)maelys_cli_json_key_string(data, "protocol", "tcp");
  (void)maelys_cli_json_key_string(data, "host", d.host);
  (void)maelys_cli_json_key_unsigned(data, "port", d.port);
  (void)maelys_cli_json_key_boolean(
      data, "requireTlsSni",
      (d.flags & MAELYS_MIR_NETWORK_DESTINATION_REQUIRE_TLS_SNI) != 0u);
  (void)maelys_cli_json_key_boolean(
      data, "allowPrivateAddresses",
      (d.flags & MAELYS_MIR_NETWORK_DESTINATION_ALLOW_PRIVATE_ADDRESSES) != 0u);
  (void)maelys_cli_json_end_object(data);
}

/* Resolves the two policies a comparison names under one host context, so
 * that the same symbolic root is the same directory in both plans. On
 * failure it has replied and returns nonzero. */
static int resolve_pair(maelys_cli_context_t *context,
                        char first_digest[MAELYS_MIR_DIGEST_HEX_SIZE],
                        maelys_sandbox_policy_plan_t **first,
                        char second_digest[MAELYS_MIR_DIGEST_HEX_SIZE],
                        maelys_sandbox_policy_plan_t **second) {
  *first = *second = NULL;
  maelys_sandbox_policy_host_t *host = host_context(context);
  if (!host)
    return 1;
  int failed = resolve_operand(context, host, maelys_cli_operand(context, 0u),
                               first_digest, first) ||
               resolve_operand(context, host, maelys_cli_operand(context, 1u),
                               second_digest, second);
  maelys_sandbox_policy_host_destroy(host);
  if (failed) {
    maelys_sandbox_policy_plan_destroy(*first);
    *first = NULL;
  }
  return failed;
}

static void write_pair_header(maelys_cli_json_writer_t *data,
                              maelys_cli_context_t *context, const char *first,
                              const char *first_digest, const char *second,
                              const char *second_digest) {
  char key[32];
  (void)maelys_cli_json_key_string(data, first, maelys_cli_operand(context, 0u));
  (void)snprintf(key, sizeof(key), "%sDigest", first);
  (void)maelys_cli_json_key_string(data, key, first_digest);
  (void)maelys_cli_json_key_string(data, second,
                                   maelys_cli_operand(context, 1u));
  (void)snprintf(key, sizeof(key), "%sDigest", second);
  (void)maelys_cli_json_key_string(data, key, second_digest);
  (void)maelys_cli_json_key_string(data, "scope", "host");
  (void)maelys_cli_json_key_unsigned(data, "permissionContract",
                                     MAELYS_SANDBOX_POLICY_PERMISSION_CONTRACT);
  write_context(data, context);
}

static void write_dimensions(maelys_cli_json_writer_t *data, const char *key,
                             unsigned dimensions) {
  static const char *const names[] = {"filesystem", "network", "root",
                                      "process"};
  (void)maelys_cli_json_key(data, key);
  (void)maelys_cli_json_begin_array(data);
  for (unsigned bit = 0; bit < 4u; ++bit)
    if (dimensions & (1u << bit))
      (void)maelys_cli_json_string(data, names[bit]);
  (void)maelys_cli_json_end_array(data);
}

static int command_contains(maelys_cli_context_t *context) {
  const char *candidate_path = maelys_cli_operand(context, 1u);
  char boundary_digest[MAELYS_MIR_DIGEST_HEX_SIZE];
  char candidate_digest[MAELYS_MIR_DIGEST_HEX_SIZE];
  maelys_sandbox_policy_plan_t *boundary = NULL, *candidate = NULL;
  if (resolve_pair(context, boundary_digest, &boundary, candidate_digest,
                   &candidate))
    return MAELYS_CLI_EXIT_FAILURE;
  maelys_sandbox_policy_containment_t found;
  char *error = NULL;
  maelys_mir_result_t result =
      maelys_sandbox_policy_plan_contains(boundary, candidate, &found, &error);
  if (result != MAELYS_MIR_OK) {
    maelys_sandbox_policy_plan_destroy(boundary);
    maelys_sandbox_policy_plan_destroy(candidate);
    return fail_mir(context, result, error, candidate_path);
  }

  char human[9000];
  size_t used = 0u;
  human[0] = '\0';
#define SAY(...)                                                               \
  do {                                                                         \
    int written = snprintf(human + used, sizeof(human) - used, __VA_ARGS__);  \
    if (written > 0 && (size_t)written < sizeof(human) - used)                 \
      used += (size_t)written;                                                 \
  } while (0)
  maelys_cli_json_writer_t data;
  maelys_cli_json_writer_init(&data);
  (void)maelys_cli_json_begin_object(&data);
  write_pair_header(&data, context, "boundary", boundary_digest, "candidate",
                    candidate_digest);
  write_analysed(&data, 1);
  (void)maelys_cli_json_key_boolean(&data, "contained", found.exceeds == 0u);
  (void)maelys_cli_json_key(&data, "exceeds");
  (void)maelys_cli_json_begin_array(&data);
  if (!found.exceeds)
    SAY("within boundary");
  if (found.exceeds & MAELYS_SANDBOX_POLICY_DIMENSION_FILESYSTEM) {
    const char *allowed =
        maelys_sandbox_policy_permission_name(found.boundary_permission);
    const char *asked =
        maelys_sandbox_policy_permission_name(found.candidate_permission);
    (void)maelys_cli_json_begin_object(&data);
    (void)maelys_cli_json_key_string(&data, "dimension", "filesystem");
    (void)maelys_cli_json_key_string(&data, "path", found.path);
    (void)maelys_cli_json_key_string(&data, "boundaryPermission", allowed);
    (void)maelys_cli_json_key_string(&data, "candidatePermission", asked);
    write_decisive_rule(&data, "boundaryRule", boundary, found.boundary_rule);
    write_decisive_rule(&data, "candidateRule", candidate, found.candidate_rule);
    (void)maelys_cli_json_end_object(&data);
    SAY("%sexceeds: filesystem: %s receives %s, the boundary gives %s",
        used ? "\n" : "", found.path, asked, allowed);
  }
  if (found.exceeds & MAELYS_SANDBOX_POLICY_DIMENSION_NETWORK) {
    static const char *const reasons[] = {"", "mode", "destination",
                                          "require-tls-sni",
                                          "allow-private-addresses"};
    (void)maelys_cli_json_begin_object(&data);
    (void)maelys_cli_json_key_string(&data, "dimension", "network");
    (void)maelys_cli_json_key_string(&data, "reason", reasons[found.network]);
    (void)maelys_cli_json_key_string(
        &data, "boundaryMode",
        network_mode_name(maelys_sandbox_policy_plan_network(boundary)));
    (void)maelys_cli_json_key_string(
        &data, "candidateMode",
        network_mode_name(maelys_sandbox_policy_plan_network(candidate)));
    SAY("%sexceeds: network: %s", used ? "\n" : "", reasons[found.network]);
    maelys_mir_network_destination_ex_view_t destination;
    if (found.candidate_destination != SIZE_MAX &&
        maelys_sandbox_policy_plan_network_destination_at_ex(
            candidate, found.candidate_destination, &destination) ==
            MAELYS_MIR_OK) {
      (void)maelys_cli_json_key(&data, "destination");
      (void)maelys_cli_json_begin_object(&data);
      (void)maelys_cli_json_key_string(&data, "protocol", "tcp");
      (void)maelys_cli_json_key_string(&data, "host", destination.host);
      (void)maelys_cli_json_key_unsigned(&data, "port", destination.port);
      (void)maelys_cli_json_end_object(&data);
      SAY(" at %s:%u", destination.host, (unsigned)destination.port);
    }
    (void)maelys_cli_json_end_object(&data);
  }
  if (found.exceeds & MAELYS_SANDBOX_POLICY_DIMENSION_ROOT) {
    (void)maelys_cli_json_begin_object(&data);
    (void)maelys_cli_json_key_string(&data, "dimension", "root");
    (void)maelys_cli_json_key_string(&data, "boundaryMode", "read-only");
    (void)maelys_cli_json_key_string(&data, "candidateMode", "ephemeral-write");
    (void)maelys_cli_json_end_object(&data);
    SAY("%sexceeds: root: ephemeral-write under a read-only boundary",
        used ? "\n" : "");
  }
  if (found.exceeds & MAELYS_SANDBOX_POLICY_DIMENSION_PROCESS) {
    (void)maelys_cli_json_begin_object(&data);
    (void)maelys_cli_json_key_string(&data, "dimension", "process");
    (void)maelys_cli_json_key_string(&data, "boundaryTreeConfinement",
                                     "required");
    (void)maelys_cli_json_key_string(&data, "candidateTreeConfinement",
                                     "disabled");
    (void)maelys_cli_json_end_object(&data);
    SAY("%sexceeds: process: tree confinement is not required",
        used ? "\n" : "");
  }
#undef SAY
  (void)maelys_cli_json_end_array(&data);
  (void)maelys_cli_json_end_object(&data);
  int exit_code = maelys_cli_succeed_writer(
      context, &data, human,
      found.exceeds ? MAELYS_CLI_EXIT_VIOLATIONS : MAELYS_CLI_EXIT_OK);
  maelys_sandbox_policy_containment_clear(&found);
  maelys_sandbox_policy_plan_destroy(boundary);
  maelys_sandbox_policy_plan_destroy(candidate);
  return exit_code;
}

/* ---- diff (report; with --check, exit 2 when the plans are not equivalent) -- */

static const maelys_cli_operand_t diff_operands[] = {
    {MAELYS_CLI_OPERAND("BEFORE", "Canonical MIR of the earlier policy.")},
    {MAELYS_CLI_OPERAND("AFTER", "Canonical MIR of the later policy.")},
};
static const maelys_cli_option_t diff_options[] = {
    HOST_CONTEXT_OPTIONS,
    {MAELYS_CLI_FLAG("check",
                     "Exit 2 when the two policies do not grant the same "
                     "permissions on this host.")},
};

static void write_change(maelys_cli_json_writer_t *data, const char *key,
                         const char *before, const char *after) {
  (void)maelys_cli_json_key(data, key);
  (void)maelys_cli_json_begin_object(data);
  (void)maelys_cli_json_key_string(data, "before", before);
  (void)maelys_cli_json_key_string(data, "after", after);
  (void)maelys_cli_json_end_object(data);
}

static const char *root_mode_name(maelys_mir_root_mode_t mode) {
  return mode == MAELYS_MIR_ROOT_EPHEMERAL_WRITE ? "ephemeral-write"
                                                 : "read-only";
}

static int command_diff(maelys_cli_context_t *context) {
  char before_digest[MAELYS_MIR_DIGEST_HEX_SIZE];
  char after_digest[MAELYS_MIR_DIGEST_HEX_SIZE];
  maelys_sandbox_policy_plan_t *before = NULL, *after = NULL;
  if (resolve_pair(context, before_digest, &before, after_digest, &after))
    return MAELYS_CLI_EXIT_FAILURE;
  maelys_sandbox_policy_diff_t *diff = NULL;
  char *error = NULL;
  maelys_mir_result_t result =
      maelys_sandbox_policy_plan_diff(before, after, &diff, &error);
  if (result != MAELYS_MIR_OK) {
    maelys_sandbox_policy_plan_destroy(before);
    maelys_sandbox_policy_plan_destroy(after);
    return fail_mir(context, result, error, maelys_cli_operand(context, 1u));
  }
  unsigned widens = maelys_sandbox_policy_diff_widens(diff);
  unsigned narrows = maelys_sandbox_policy_diff_narrows(diff);
  int equivalent = !widens && !narrows;

  maelys_cli_json_writer_t data;
  maelys_cli_json_writer_init(&data);
  (void)maelys_cli_json_begin_object(&data);
  write_pair_header(&data, context, "before", before_digest, "after",
                    after_digest);
  write_analysed(&data, 1);
  (void)maelys_cli_json_key_boolean(&data, "equivalent", equivalent);
  write_dimensions(&data, "widens", widens);
  write_dimensions(&data, "narrows", narrows);
  (void)maelys_cli_json_key(&data, "filesystem");
  (void)maelys_cli_json_begin_array(&data);
  for (size_t i = 0; i < maelys_sandbox_policy_diff_path_count(diff); ++i) {
    maelys_sandbox_policy_diff_path_view_t entry;
    if (maelys_sandbox_policy_diff_path_at(diff, i, &entry) != MAELYS_MIR_OK)
      continue;
    (void)maelys_cli_json_begin_object(&data);
    (void)maelys_cli_json_key_string(&data, "path", entry.path);
    write_change(&data, "self",
                 maelys_sandbox_policy_permission_name(entry.self_before),
                 maelys_sandbox_policy_permission_name(entry.self_after));
    write_change(&data, "below",
                 maelys_sandbox_policy_permission_name(entry.below_before),
                 maelys_sandbox_policy_permission_name(entry.below_after));
    (void)maelys_cli_json_end_object(&data);
  }
  (void)maelys_cli_json_end_array(&data);
  (void)maelys_cli_json_key(&data, "network");
  (void)maelys_cli_json_begin_object(&data);
  write_change(&data, "mode",
               network_mode_name(maelys_sandbox_policy_plan_network(before)),
               network_mode_name(maelys_sandbox_policy_plan_network(after)));
  (void)maelys_cli_json_key(&data, "added");
  (void)maelys_cli_json_begin_array(&data);
  for (size_t i = 0;
       i < maelys_sandbox_policy_diff_added_destination_count(diff); ++i)
    write_destination(
        &data, after, maelys_sandbox_policy_diff_added_destination_at(diff, i));
  (void)maelys_cli_json_end_array(&data);
  (void)maelys_cli_json_key(&data, "removed");
  (void)maelys_cli_json_begin_array(&data);
  for (size_t i = 0;
       i < maelys_sandbox_policy_diff_removed_destination_count(diff); ++i)
    write_destination(
        &data, before,
        maelys_sandbox_policy_diff_removed_destination_at(diff, i));
  (void)maelys_cli_json_end_array(&data);
  (void)maelys_cli_json_end_object(&data);
  write_change(&data, "root",
               root_mode_name(maelys_sandbox_policy_plan_root_mode(before)),
               root_mode_name(maelys_sandbox_policy_plan_root_mode(after)));
  write_change(
      &data, "process",
      maelys_sandbox_policy_plan_process_tree_required(before) ? "required"
                                                               : "disabled",
      maelys_sandbox_policy_plan_process_tree_required(after) ? "required"
                                                              : "disabled");
  (void)maelys_cli_json_end_object(&data);
  int exit_code = maelys_cli_succeed_writer(
      context, &data, NULL,
      maelys_cli_flag(context, "check") && !equivalent
          ? MAELYS_CLI_EXIT_VIOLATIONS
          : MAELYS_CLI_EXIT_OK);
  maelys_sandbox_policy_diff_destroy(diff);
  maelys_sandbox_policy_plan_destroy(before);
  maelys_sandbox_policy_plan_destroy(after);
  return exit_code;
}

/* ---- overlaps (is there an access both policies grant?) -------------------- */

static const maelys_cli_operand_t overlaps_operands[] = {
    {MAELYS_CLI_OPERAND("FIRST", "Canonical MIR of one policy.")},
    {MAELYS_CLI_OPERAND("SECOND", "Canonical MIR of the other policy.")},
};

static int command_overlaps(maelys_cli_context_t *context) {
  char first_digest[MAELYS_MIR_DIGEST_HEX_SIZE];
  char second_digest[MAELYS_MIR_DIGEST_HEX_SIZE];
  maelys_sandbox_policy_plan_t *first = NULL, *second = NULL;
  if (resolve_pair(context, first_digest, &first, second_digest, &second))
    return MAELYS_CLI_EXIT_FAILURE;
  maelys_sandbox_policy_overlap_t overlap;
  char *error = NULL;
  maelys_mir_result_t result =
      maelys_sandbox_policy_plan_overlaps(first, second, &overlap, &error);
  if (result != MAELYS_MIR_OK) {
    maelys_sandbox_policy_plan_destroy(first);
    maelys_sandbox_policy_plan_destroy(second);
    return fail_mir(context, result, error, maelys_cli_operand(context, 1u));
  }
  int network =
      (overlap.dimensions & MAELYS_SANDBOX_POLICY_DIMENSION_NETWORK) != 0u;
  maelys_cli_json_writer_t data;
  maelys_cli_json_writer_init(&data);
  (void)maelys_cli_json_begin_object(&data);
  write_pair_header(&data, context, "first", first_digest, "second",
                    second_digest);
  write_analysed(&data, 0);
  (void)maelys_cli_json_key_boolean(&data, "overlaps", overlap.dimensions != 0u);
  (void)maelys_cli_json_key(&data, "filesystem");
  (void)maelys_cli_json_begin_object(&data);
  if (overlap.read_path)
    (void)maelys_cli_json_key_string(&data, "readablePath", overlap.read_path);
  if (overlap.write_path)
    (void)maelys_cli_json_key_string(&data, "writablePath", overlap.write_path);
  (void)maelys_cli_json_end_object(&data);
  (void)maelys_cli_json_key(&data, "network");
  (void)maelys_cli_json_begin_object(&data);
  (void)maelys_cli_json_key_boolean(&data, "overlaps", network);
  if (overlap.first_destination != SIZE_MAX) {
    (void)maelys_cli_json_key(&data, "firstDestination");
    write_destination(&data, first, overlap.first_destination);
  }
  if (overlap.second_destination != SIZE_MAX) {
    (void)maelys_cli_json_key(&data, "secondDestination");
    write_destination(&data, second, overlap.second_destination);
  }
  (void)maelys_cli_json_end_object(&data);
  (void)maelys_cli_json_end_object(&data);
  char human[9000];
  if (!overlap.dimensions)
    (void)snprintf(human, sizeof(human), "no common access");
  else
    (void)snprintf(human, sizeof(human),
                   "common access: readable %s; writable %s; network %s",
                   overlap.read_path ? overlap.read_path : "none",
                   overlap.write_path ? overlap.write_path : "none",
                   network ? "yes" : "no");
  int exit_code =
      maelys_cli_succeed_writer(context, &data, human, MAELYS_CLI_EXIT_OK);
  maelys_sandbox_policy_overlap_clear(&overlap);
  maelys_sandbox_policy_plan_destroy(first);
  maelys_sandbox_policy_plan_destroy(second);
  return exit_code;
}

/* ---- validate (report, exit 2 on violation) -------------------------------- */

static const maelys_cli_operand_t policy_operands[] = {
    {MAELYS_CLI_OPERAND("POLICY", "Canonical MIR file.")},
};

static int command_validate(maelys_cli_context_t *context) {
  const char *path = maelys_cli_operand(context, 0u);
  unsigned char *bytes = NULL;
  size_t size = 0u;
  if (read_input(context, path, &bytes, &size) != 0)
    return MAELYS_CLI_EXIT_FAILURE;
  maelys_mir_t *mir = NULL;
  char *error = NULL;
  maelys_mir_result_t result = maelys_mir_decode(bytes, size, &mir, &error);
  free(bytes);
  char digest[MAELYS_MIR_DIGEST_HEX_SIZE] = "";
  if (result == MAELYS_MIR_OK)
    result = maelys_mir_digest_hex(mir, digest, &error);
  maelys_mir_destroy(mir);
  if (result == MAELYS_MIR_ERR_MEMORY)
    return fail_mir(context, result, error, path);
  int valid = result == MAELYS_MIR_OK;

  maelys_cli_json_writer_t data;
  maelys_cli_json_writer_init(&data);
  (void)maelys_cli_json_begin_object(&data);
  (void)maelys_cli_json_key_boolean(&data, "valid", valid);
  (void)maelys_cli_json_key_string(&data, "path", path);
  (void)maelys_cli_json_key_unsigned(&data, "formatVersion",
                                     MAELYS_MIR_FORMAT_VERSION);
  if (valid)
    (void)maelys_cli_json_key_string(&data, "digest", digest);
  (void)maelys_cli_json_key(&data, "diagnostics");
  (void)maelys_cli_json_begin_array(&data);
  char human[1024];
  if (valid) {
    (void)snprintf(human, sizeof(human), "valid MIR v%u",
                   MAELYS_MIR_FORMAT_VERSION);
  } else {
    char code[32] = "MIR_";
    const char *name = maelys_mir_result_name(result);
    for (size_t i = 0u; name[i] && i + 5u < sizeof(code); ++i)
      code[4u + i] = (char)(name[i] >= 'a' && name[i] <= 'z'
                                ? name[i] - 'a' + 'A'
                                : name[i]);
    const char *message = error ? error : "no diagnostic";
    (void)maelys_cli_json_begin_object(&data);
    (void)maelys_cli_json_key_string(&data, "code", code);
    (void)maelys_cli_json_key_string(&data, "message", message);
    (void)maelys_cli_json_end_object(&data);
    (void)snprintf(human, sizeof(human), "invalid MIR v%u: %s",
                   MAELYS_MIR_FORMAT_VERSION, message);
  }
  maelys_mir_error_free(error);
  (void)maelys_cli_json_end_array(&data);
  (void)maelys_cli_json_end_object(&data);
  return maelys_cli_succeed_writer(
      context, &data, human,
      valid ? MAELYS_CLI_EXIT_OK : MAELYS_CLI_EXIT_VIOLATIONS);
}

/* ---- hash, artifact-hash, inspect ------------------------------------------ */

static int command_hash(maelys_cli_context_t *context) {
  maelys_mir_t *mir = NULL;
  const char *path = maelys_cli_operand(context, 0u);
  if (decode_policy(context, path, &mir) != MAELYS_CLI_EXIT_OK)
    return MAELYS_CLI_EXIT_FAILURE;
  char digest[MAELYS_MIR_DIGEST_HEX_SIZE];
  char *error = NULL;
  maelys_mir_result_t result = maelys_mir_digest_hex(mir, digest, &error);
  maelys_mir_destroy(mir);
  if (result != MAELYS_MIR_OK)
    return fail_mir(context, result, error, path);
  return succeed_digest(context, digest);
}

static const maelys_cli_operand_t artifact_operands[] = {
    {MAELYS_CLI_OPERAND("FILE", "Any artifact, such as a policy source.")},
};

static int command_artifact_hash(maelys_cli_context_t *context) {
  const char *path = maelys_cli_operand(context, 0u);
  unsigned char *bytes = NULL;
  size_t size = 0u;
  if (read_input(context, path, &bytes, &size) != 0)
    return MAELYS_CLI_EXIT_FAILURE;
  char digest[MAELYS_MIR_DIGEST_HEX_SIZE];
  char *error = NULL;
  maelys_mir_result_t result =
      maelys_mir_artifact_digest_hex(bytes, size, digest, &error);
  free(bytes);
  if (result != MAELYS_MIR_OK)
    return fail_mir(context, result, error, path);
  return succeed_digest(context, digest);
}

static int command_inspect(maelys_cli_context_t *context) {
  maelys_mir_t *mir = NULL;
  const char *path = maelys_cli_operand(context, 0u);
  if (decode_policy(context, path, &mir) != MAELYS_CLI_EXIT_OK)
    return MAELYS_CLI_EXIT_FAILURE;
  uint8_t *json = NULL;
  size_t size = 0u;
  char *error = NULL;
  maelys_mir_result_t result = maelys_mir_inspect_json(mir, &json, &size, &error);
  maelys_mir_destroy(mir);
  if (result != MAELYS_MIR_OK)
    return fail_mir(context, result, error, path);
  /* The projection is its own deterministic text: it is the human form, and
   * as data it is validated and re-rendered like any other object. */
  char *text = malloc(size + 1u);
  if (!text) {
    maelys_mir_bytes_free(json);
    return maelys_cli_fail_errno(context, MAELYS_CLI_CODE_UNEXPECTED, ENOMEM,
                                 "inspection");
  }
  memcpy(text, json, size);
  text[size] = '\0';
  maelys_mir_bytes_free(json);
  if (size > 0u && text[size - 1u] == '\n')
    text[size - 1u] = '\0';
  int exit_code = maelys_cli_succeed(context, text, text, MAELYS_CLI_EXIT_OK);
  free(text);
  return exit_code;
}

/* ---- catalog ---------------------------------------------------------------- */

/* One line to copy per command; the catalog refuses one the command would
 * not accept. Paths are illustrative: nothing is read at startup. */
static const maelys_cli_example_t compile_examples[] = {
    {MAELYS_CLI_EXAMPLE("compile examples/workspace.json --output policy.mir",
                        "Plan the compilation: nothing is written, and the plan "
                        "carries the fingerprint --expect takes.")},
    {MAELYS_CLI_EXAMPLE(
        "compile examples/workspace.json --output policy.mir --apply",
        "Write the canonical MIR.")},
};
static const maelys_cli_example_t restrict_examples[] = {
    {MAELYS_CLI_EXAMPLE(
        "restrict policy.mir ceiling.mir --output effective.mir --apply",
        "Write a policy that grants nothing policy.mir or ceiling.mir did not.")},
};
static const maelys_cli_example_t capabilities_examples[] = {
    {MAELYS_CLI_EXAMPLE("capabilities policy.mir",
                        "List what a backend must offer to apply the policy.")},
    {MAELYS_CLI_EXAMPLE(
        "capabilities policy.mir --check --available fs-read --available fs-write",
        "Exit 2 when the policy needs more than the two capabilities named.")},
};
static const maelys_cli_example_t resolve_examples[] = {
    {MAELYS_CLI_EXAMPLE(
        "resolve policy.mir --workspace /work --minimal-root /usr",
        "The rules on this host, with what was omitted and what blocks.")},
};
static const maelys_cli_example_t evaluate_examples[] = {
    {MAELYS_CLI_EXAMPLE("evaluate policy.mir --workspace /work --minimal-root "
                        "/usr --path /work/src/main.c",
                        "What the policy grants on one path, and why.")},
};
static const maelys_cli_example_t contains_examples[] = {
    {MAELYS_CLI_EXAMPLE(
        "contains parent.mir child.mir --workspace /work --minimal-root /usr",
        "Exit 2, with a witness, when child.mir grants what parent.mir does not.")},
};
static const maelys_cli_example_t diff_examples[] = {
    {MAELYS_CLI_EXAMPLE(
        "diff before.mir after.mir --workspace /work --minimal-root /usr",
        "What changes between the two policies on this host.")},
    {MAELYS_CLI_EXAMPLE(
        "diff before.mir after.mir --workspace /work --minimal-root /usr --check",
        "Exit 2 unless the two policies are equivalent here.")},
};
static const maelys_cli_example_t overlaps_examples[] = {
    {MAELYS_CLI_EXAMPLE(
        "overlaps first.mir second.mir --workspace /work --minimal-root /usr",
        "Whether both policies grant a common access, and where.")},
};
static const maelys_cli_example_t validate_examples[] = {
    {MAELYS_CLI_EXAMPLE("validate policy.mir",
                        "Exit 2 when the file is not canonical MIR.")},
};
static const maelys_cli_example_t hash_examples[] = {
    {MAELYS_CLI_EXAMPLE("hash policy.mir", "The policy identity, a SHA-256.")},
};
static const maelys_cli_example_t inspect_examples[] = {
    {MAELYS_CLI_EXAMPLE("inspect policy.mir --format json",
                        "The decoded policy as JSON.")},
};
static const maelys_cli_example_t artifact_hash_examples[] = {
    {MAELYS_CLI_EXAMPLE("artifact-hash examples/workspace.json",
                        "The identity a source would compile to, without writing it.")},
};

static const maelys_cli_command_t commands[] = {
    {MAELYS_CLI_TRANSACTION("compile", "compile",
                            "Compile a JSON policy source into canonical MIR.",
                            command_compile),
     MAELYS_CLI_OPERANDS(compile_operands), MAELYS_CLI_OPTIONS(publish_options),
     MAELYS_CLI_SCHEMA(policy_compile_schema),
     MAELYS_CLI_EXAMPLES(compile_examples)},
    {MAELYS_CLI_TRANSACTION("restrict", "restrict",
                            "Compose a restriction over a base policy; the "
                            "result grants nothing the base did not.",
                            command_restrict),
     MAELYS_CLI_OPERANDS(restrict_operands), MAELYS_CLI_OPTIONS(publish_options),
     MAELYS_CLI_SCHEMA(policy_restrict_schema),
     MAELYS_CLI_EXAMPLES(restrict_examples)},
    {MAELYS_CLI_READ("capabilities", "capabilities",
                     "List the backend capabilities a policy requires, or "
                     "check them against a declared set; exit 2 when some "
                     "are missing.",
                     command_capabilities),
     MAELYS_CLI_OPERANDS(policy_operands),
     MAELYS_CLI_OPTIONS(capabilities_options),
     MAELYS_CLI_SCHEMA(policy_capabilities_schema),
     MAELYS_CLI_EXAMPLES(capabilities_examples)},
    {MAELYS_CLI_READ("resolve", "resolve",
                     "Resolve a policy on this host and report its rules, "
                     "what was omitted and what prevents the execution; "
                     "exit 2 when something does.",
                     command_resolve),
     MAELYS_CLI_OPERANDS(policy_operands), MAELYS_CLI_OPTIONS(resolve_options),
     MAELYS_CLI_SCHEMA(policy_resolve_schema),
     MAELYS_CLI_EXAMPLES(resolve_examples)},
    {MAELYS_CLI_READ("evaluate", "evaluate",
                     "State what the policy, resolved on this host, grants "
                     "on one path, and the rule that decides.",
                     command_evaluate),
     MAELYS_CLI_OPERANDS(policy_operands), MAELYS_CLI_OPTIONS(evaluate_options),
     MAELYS_CLI_SCHEMA(policy_evaluate_schema),
     MAELYS_CLI_EXAMPLES(evaluate_examples)},
    {MAELYS_CLI_READ("contains", "contains",
                     "Check that a candidate policy, resolved on this host, "
                     "grants nothing its boundary does not; exit 2 with a "
                     "witness when it does.",
                     command_contains),
     MAELYS_CLI_OPERANDS(contains_operands), MAELYS_CLI_OPTIONS(contains_options),
     MAELYS_CLI_SCHEMA(policy_contains_schema),
     MAELYS_CLI_EXAMPLES(contains_examples)},
    {MAELYS_CLI_READ("diff", "diff",
                     "Report what changes between two policies resolved on "
                     "this host; with --check, exit 2 unless they grant the "
                     "same permissions.",
                     command_diff),
     MAELYS_CLI_OPERANDS(diff_operands), MAELYS_CLI_OPTIONS(diff_options),
     MAELYS_CLI_SCHEMA(policy_diff_schema),
     MAELYS_CLI_EXAMPLES(diff_examples)},
    {MAELYS_CLI_READ("overlaps", "overlaps",
                     "Tell whether two policies resolved on this host grant "
                     "a common access, with a witness.",
                     command_overlaps),
     MAELYS_CLI_OPERANDS(overlaps_operands), MAELYS_CLI_OPTIONS(contains_options),
     MAELYS_CLI_SCHEMA(policy_overlaps_schema),
     MAELYS_CLI_EXAMPLES(overlaps_examples)},
    {MAELYS_CLI_READ("validate", "validate",
                     "Check that a file is canonical MIR; exit 2 when it is not.",
                     command_validate),
     MAELYS_CLI_OPERANDS(policy_operands),
     MAELYS_CLI_SCHEMA(policy_validate_schema),
     MAELYS_CLI_EXAMPLES(validate_examples)},
    {MAELYS_CLI_READ("hash", "hash",
                     "Print the decision digest of canonical MIR.", command_hash),
     MAELYS_CLI_OPERANDS(policy_operands), MAELYS_CLI_SCHEMA(policy_hash_schema),
     MAELYS_CLI_EXAMPLES(hash_examples)},
    {MAELYS_CLI_READ("inspect", "inspect",
                     "Render the non-normative JSON projection of canonical MIR.",
                     command_inspect),
     MAELYS_CLI_OPERANDS(policy_operands),
     MAELYS_CLI_SCHEMA(policy_inspect_schema),
     MAELYS_CLI_EXAMPLES(inspect_examples)},
    {MAELYS_CLI_READ("artifact-hash", "artifact-hash",
                     "Print the SHA-256 of any file; it carries no policy "
                     "identity.",
                     command_artifact_hash),
     MAELYS_CLI_OPERANDS(artifact_operands),
     MAELYS_CLI_SCHEMA(policy_hash_schema),
     MAELYS_CLI_EXAMPLES(artifact_hash_examples)},
};

int main(int argc, char **argv) {
  static const maelys_cli_app_t app = {
      .program = "maelys-policy",
      .product = "Maelys Sandbox Policy",
      .version = MAELYS_SANDBOX_POLICY_VERSION,
      .summary = "compile and verify canonical Maelys sandbox policies",
      .commands = commands,
      .command_count = MAELYS_CLI_COUNT(commands),
  };
  return maelys_cli_main(&app, argc, argv);
}
