/* Generated by scripts/freeze_abi.py from v0.6.0: include/maelys/sandbox_policy.h.
 * Do not edit. Include after the current headers, once with
 * MAELYS_ABI_FLOOR_PRESENCE defined and once without. While this compiles,
 * every declaration of that revision still holds as it was: it is the
 * floor the ABI_COMPATIBLE_SINCE macro names. Regenerate only when a
 * break raises that floor, in the same change that raises the macro. */
#include <stddef.h>
#ifdef MAELYS_ABI_FLOOR_PRESENCE
void abi_sandbox_policy_5_presence(void);
void abi_sandbox_policy_5_presence(void) {
    (void)sizeof(maelys_sandbox_policy_host_t *);
    (void)sizeof(maelys_sandbox_policy_plan_t *);
    (void)sizeof(maelys_sandbox_policy_capabilities_t *);
    (void)sizeof(maelys_sandbox_policy_missing_t *);
    (void)sizeof(maelys_sandbox_policy_resolved_rule_view_t *);
    (void)sizeof(maelys_sandbox_policy_permission_t *);
    (void)sizeof(maelys_sandbox_policy_reason_t *);
    (void)sizeof(maelys_sandbox_policy_evaluation_t *);
    (void)sizeof(maelys_sandbox_policy_omitted_rule_view_t *);
    (void)maelys_sandbox_policy_host_create;
    (void)maelys_sandbox_policy_host_destroy;
    (void)maelys_sandbox_policy_host_set_workspace;
    (void)maelys_sandbox_policy_host_set_temp;
    (void)maelys_sandbox_policy_host_add_minimal_runtime_root;
    (void)maelys_sandbox_policy_host_set_network_mediator;
    (void)maelys_sandbox_policy_required_capabilities;
    (void)maelys_sandbox_policy_resolved_capabilities;
    (void)maelys_sandbox_policy_capability_name;
    (void)maelys_sandbox_policy_plan_required_capabilities;
    (void)maelys_sandbox_policy_check_support;
    (void)maelys_sandbox_policy_compile;
    (void)maelys_sandbox_policy_plan_destroy;
    (void)maelys_sandbox_policy_plan_rule_count;
    (void)maelys_sandbox_policy_plan_rule_at;
    (void)maelys_sandbox_policy_plan_evaluate;
    (void)maelys_sandbox_policy_permission_name;
    (void)maelys_sandbox_policy_reason_name;
    (void)maelys_sandbox_policy_plan_omitted_rule_count;
    (void)maelys_sandbox_policy_plan_omitted_rule_at;
    (void)maelys_sandbox_policy_plan_network;
    (void)maelys_sandbox_policy_plan_root_mode;
    (void)maelys_sandbox_policy_plan_network_mediator;
    (void)maelys_sandbox_policy_plan_network_destination_count;
    (void)maelys_sandbox_policy_plan_network_destination_at;
    (void)maelys_sandbox_policy_plan_network_destination_at_ex;
    (void)maelys_sandbox_policy_plan_process_tree_required;
    (void)maelys_sandbox_policy_plan_mir_digest;
}
#else

/* include/maelys/sandbox_policy.h at v0.6.0 */
_Static_assert((MAELYS_SANDBOX_POLICY_PERMISSION_CONTRACT) == (2u), "MAELYS_SANDBOX_POLICY_PERMISSION_CONTRACT changed since v0.6.0");
typedef struct maelys_sandbox_policy_host maelys_sandbox_policy_host_t;
typedef struct maelys_sandbox_policy_plan maelys_sandbox_policy_plan_t;
typedef uint64_t maelys_sandbox_policy_capabilities_t;
_Static_assert(MAELYS_SANDBOX_POLICY_CAP_FS_READ == (UINT64_C(1) << 0) + 0, "MAELYS_SANDBOX_POLICY_CAP_FS_READ moved since v0.6.0");
_Static_assert(MAELYS_SANDBOX_POLICY_CAP_FS_WRITE == (UINT64_C(1) << 1) + 0, "MAELYS_SANDBOX_POLICY_CAP_FS_WRITE moved since v0.6.0");
_Static_assert(MAELYS_SANDBOX_POLICY_CAP_FS_DENY == (UINT64_C(1) << 2) + 0, "MAELYS_SANDBOX_POLICY_CAP_FS_DENY moved since v0.6.0");
_Static_assert(MAELYS_SANDBOX_POLICY_CAP_NETWORK_NONE == (UINT64_C(1) << 3) + 0, "MAELYS_SANDBOX_POLICY_CAP_NETWORK_NONE moved since v0.6.0");
_Static_assert(MAELYS_SANDBOX_POLICY_CAP_NETWORK_DIRECT == (UINT64_C(1) << 4) + 0, "MAELYS_SANDBOX_POLICY_CAP_NETWORK_DIRECT moved since v0.6.0");
_Static_assert(MAELYS_SANDBOX_POLICY_CAP_NETWORK_MEDIATED == (UINT64_C(1) << 5) + 0, "MAELYS_SANDBOX_POLICY_CAP_NETWORK_MEDIATED moved since v0.6.0");
_Static_assert(MAELYS_SANDBOX_POLICY_CAP_PROCESS_TREE == (UINT64_C(1) << 6) + 0, "MAELYS_SANDBOX_POLICY_CAP_PROCESS_TREE moved since v0.6.0");
_Static_assert(MAELYS_SANDBOX_POLICY_CAP_ROOT_EPHEMERAL_WRITE == (UINT64_C(1) << 7) + 0, "MAELYS_SANDBOX_POLICY_CAP_ROOT_EPHEMERAL_WRITE moved since v0.6.0");
_Static_assert(MAELYS_SANDBOX_POLICY_CAP_NETWORK_REQUIRE_TLS_SNI == (UINT64_C(1) << 8) + 0, "MAELYS_SANDBOX_POLICY_CAP_NETWORK_REQUIRE_TLS_SNI moved since v0.6.0");
_Static_assert(MAELYS_SANDBOX_POLICY_CAP_NETWORK_PRIVATE_ADDRESSES == (UINT64_C(1) << 9) + 0, "MAELYS_SANDBOX_POLICY_CAP_NETWORK_PRIVATE_ADDRESSES moved since v0.6.0");
_Static_assert(MAELYS_SANDBOX_POLICY_CAP_FS_PROTECT_CREATE == (UINT64_C(1) << 10) + 0, "MAELYS_SANDBOX_POLICY_CAP_FS_PROTECT_CREATE moved since v0.6.0");
_Static_assert(MAELYS_SANDBOX_POLICY_MISSING_ERROR == (1) + 0, "MAELYS_SANDBOX_POLICY_MISSING_ERROR moved since v0.6.0");
_Static_assert(MAELYS_SANDBOX_POLICY_MISSING_PROTECT_CREATE == (2) + 0, "MAELYS_SANDBOX_POLICY_MISSING_PROTECT_CREATE moved since v0.6.0");
typedef struct frozen_maelys_sandbox_policy_resolved_rule_view {
    maelys_mir_fs_access_t access;
    maelys_mir_path_scope_t scope;
    const char *path;
    maelys_sandbox_policy_missing_t missing;
} frozen_maelys_sandbox_policy_resolved_rule_view_t;
_Static_assert(sizeof(maelys_sandbox_policy_resolved_rule_view_t) == sizeof(frozen_maelys_sandbox_policy_resolved_rule_view_t), "maelys_sandbox_policy_resolved_rule_view_t changed size since v0.6.0");
_Static_assert(offsetof(maelys_sandbox_policy_resolved_rule_view_t, access) == offsetof(frozen_maelys_sandbox_policy_resolved_rule_view_t, access), "maelys_sandbox_policy_resolved_rule_view_t.access moved since v0.6.0");
_Static_assert(offsetof(maelys_sandbox_policy_resolved_rule_view_t, scope) == offsetof(frozen_maelys_sandbox_policy_resolved_rule_view_t, scope), "maelys_sandbox_policy_resolved_rule_view_t.scope moved since v0.6.0");
_Static_assert(offsetof(maelys_sandbox_policy_resolved_rule_view_t, path) == offsetof(frozen_maelys_sandbox_policy_resolved_rule_view_t, path), "maelys_sandbox_policy_resolved_rule_view_t.path moved since v0.6.0");
_Static_assert(offsetof(maelys_sandbox_policy_resolved_rule_view_t, missing) == offsetof(frozen_maelys_sandbox_policy_resolved_rule_view_t, missing), "maelys_sandbox_policy_resolved_rule_view_t.missing moved since v0.6.0");
_Static_assert(MAELYS_SANDBOX_POLICY_PERMISSION_NONE == (0) + 0, "MAELYS_SANDBOX_POLICY_PERMISSION_NONE moved since v0.6.0");
_Static_assert(MAELYS_SANDBOX_POLICY_PERMISSION_READ == (1) + 0, "MAELYS_SANDBOX_POLICY_PERMISSION_READ moved since v0.6.0");
_Static_assert(MAELYS_SANDBOX_POLICY_PERMISSION_READ_WRITE == (2) + 0, "MAELYS_SANDBOX_POLICY_PERMISSION_READ_WRITE moved since v0.6.0");
_Static_assert(MAELYS_SANDBOX_POLICY_REASON_DEFAULT_DENY == (1) + 0, "MAELYS_SANDBOX_POLICY_REASON_DEFAULT_DENY moved since v0.6.0");
_Static_assert(MAELYS_SANDBOX_POLICY_REASON_DENY_RULE == (2) + 0, "MAELYS_SANDBOX_POLICY_REASON_DENY_RULE moved since v0.6.0");
_Static_assert(MAELYS_SANDBOX_POLICY_REASON_WRITE_RULE == (3) + 0, "MAELYS_SANDBOX_POLICY_REASON_WRITE_RULE moved since v0.6.0");
_Static_assert(MAELYS_SANDBOX_POLICY_REASON_READ_RULE == (4) + 0, "MAELYS_SANDBOX_POLICY_REASON_READ_RULE moved since v0.6.0");
typedef struct frozen_maelys_sandbox_policy_evaluation {
    maelys_sandbox_policy_permission_t permission;
    maelys_sandbox_policy_reason_t reason;
    size_t decisive_rule;
    size_t applicable_rule_count;
} frozen_maelys_sandbox_policy_evaluation_t;
_Static_assert(sizeof(maelys_sandbox_policy_evaluation_t) == sizeof(frozen_maelys_sandbox_policy_evaluation_t), "maelys_sandbox_policy_evaluation_t changed size since v0.6.0");
_Static_assert(offsetof(maelys_sandbox_policy_evaluation_t, permission) == offsetof(frozen_maelys_sandbox_policy_evaluation_t, permission), "maelys_sandbox_policy_evaluation_t.permission moved since v0.6.0");
_Static_assert(offsetof(maelys_sandbox_policy_evaluation_t, reason) == offsetof(frozen_maelys_sandbox_policy_evaluation_t, reason), "maelys_sandbox_policy_evaluation_t.reason moved since v0.6.0");
_Static_assert(offsetof(maelys_sandbox_policy_evaluation_t, decisive_rule) == offsetof(frozen_maelys_sandbox_policy_evaluation_t, decisive_rule), "maelys_sandbox_policy_evaluation_t.decisive_rule moved since v0.6.0");
_Static_assert(offsetof(maelys_sandbox_policy_evaluation_t, applicable_rule_count) == offsetof(frozen_maelys_sandbox_policy_evaluation_t, applicable_rule_count), "maelys_sandbox_policy_evaluation_t.applicable_rule_count moved since v0.6.0");
maelys_mir_result_t maelys_sandbox_policy_host_create(maelys_sandbox_policy_host_t **out_host, char **out_error);
void maelys_sandbox_policy_host_destroy(maelys_sandbox_policy_host_t *host);
maelys_mir_result_t maelys_sandbox_policy_host_set_workspace(maelys_sandbox_policy_host_t *host, const char *path, char **out_error);
maelys_mir_result_t maelys_sandbox_policy_host_set_temp(maelys_sandbox_policy_host_t *host, const char *path, char **out_error);
maelys_mir_result_t maelys_sandbox_policy_host_add_minimal_runtime_root( maelys_sandbox_policy_host_t *host, const char *path, char **out_error);
maelys_mir_result_t maelys_sandbox_policy_host_set_network_mediator( maelys_sandbox_policy_host_t *host, const char *mediator_id, char **out_error);
maelys_sandbox_policy_capabilities_t maelys_sandbox_policy_required_capabilities(const maelys_mir_t *mir);
maelys_mir_result_t maelys_sandbox_policy_resolved_capabilities( const maelys_mir_t *mir, const maelys_sandbox_policy_host_t *host, maelys_sandbox_policy_capabilities_t *out_required, char **out_error);
const char * maelys_sandbox_policy_capability_name(maelys_sandbox_policy_capabilities_t capability);
maelys_sandbox_policy_capabilities_t maelys_sandbox_policy_plan_required_capabilities( const maelys_sandbox_policy_plan_t *plan);
maelys_mir_result_t maelys_sandbox_policy_check_support(const maelys_mir_t *mir, maelys_sandbox_policy_capabilities_t available, char **out_error);
maelys_mir_result_t maelys_sandbox_policy_compile(const maelys_mir_t *mir, const maelys_sandbox_policy_host_t *host, maelys_sandbox_policy_capabilities_t available, maelys_sandbox_policy_plan_t **out_plan, char **out_error);
void maelys_sandbox_policy_plan_destroy(maelys_sandbox_policy_plan_t *plan);
size_t maelys_sandbox_policy_plan_rule_count(const maelys_sandbox_policy_plan_t *plan);
maelys_mir_result_t maelys_sandbox_policy_plan_rule_at(const maelys_sandbox_policy_plan_t *plan, size_t index, maelys_sandbox_policy_resolved_rule_view_t *out_rule);
maelys_mir_result_t maelys_sandbox_policy_plan_evaluate( const maelys_sandbox_policy_plan_t *plan, const char *absolute_path, maelys_sandbox_policy_evaluation_t *out_evaluation, char **out_error);
const char * maelys_sandbox_policy_permission_name(maelys_sandbox_policy_permission_t value);
const char * maelys_sandbox_policy_reason_name(maelys_sandbox_policy_reason_t value);
typedef struct frozen_maelys_sandbox_policy_omitted_rule_view {
    maelys_mir_fs_access_t access;
    maelys_mir_path_scope_t scope;
    maelys_mir_path_root_t root;
    const char *relative;
    const char *host_root;
} frozen_maelys_sandbox_policy_omitted_rule_view_t;
_Static_assert(sizeof(maelys_sandbox_policy_omitted_rule_view_t) == sizeof(frozen_maelys_sandbox_policy_omitted_rule_view_t), "maelys_sandbox_policy_omitted_rule_view_t changed size since v0.6.0");
_Static_assert(offsetof(maelys_sandbox_policy_omitted_rule_view_t, access) == offsetof(frozen_maelys_sandbox_policy_omitted_rule_view_t, access), "maelys_sandbox_policy_omitted_rule_view_t.access moved since v0.6.0");
_Static_assert(offsetof(maelys_sandbox_policy_omitted_rule_view_t, scope) == offsetof(frozen_maelys_sandbox_policy_omitted_rule_view_t, scope), "maelys_sandbox_policy_omitted_rule_view_t.scope moved since v0.6.0");
_Static_assert(offsetof(maelys_sandbox_policy_omitted_rule_view_t, root) == offsetof(frozen_maelys_sandbox_policy_omitted_rule_view_t, root), "maelys_sandbox_policy_omitted_rule_view_t.root moved since v0.6.0");
_Static_assert(offsetof(maelys_sandbox_policy_omitted_rule_view_t, relative) == offsetof(frozen_maelys_sandbox_policy_omitted_rule_view_t, relative), "maelys_sandbox_policy_omitted_rule_view_t.relative moved since v0.6.0");
_Static_assert(offsetof(maelys_sandbox_policy_omitted_rule_view_t, host_root) == offsetof(frozen_maelys_sandbox_policy_omitted_rule_view_t, host_root), "maelys_sandbox_policy_omitted_rule_view_t.host_root moved since v0.6.0");
size_t maelys_sandbox_policy_plan_omitted_rule_count( const maelys_sandbox_policy_plan_t *plan);
maelys_mir_result_t maelys_sandbox_policy_plan_omitted_rule_at( const maelys_sandbox_policy_plan_t *plan, size_t index, maelys_sandbox_policy_omitted_rule_view_t *out_rule);
maelys_mir_network_mode_t maelys_sandbox_policy_plan_network(const maelys_sandbox_policy_plan_t *plan);
maelys_mir_root_mode_t maelys_sandbox_policy_plan_root_mode( const maelys_sandbox_policy_plan_t *plan);
const char * maelys_sandbox_policy_plan_network_mediator(const maelys_sandbox_policy_plan_t *plan);
size_t maelys_sandbox_policy_plan_network_destination_count( const maelys_sandbox_policy_plan_t *plan);
maelys_mir_result_t maelys_sandbox_policy_plan_network_destination_at( const maelys_sandbox_policy_plan_t *plan, size_t index, maelys_mir_network_destination_view_t *out_destination);
maelys_mir_result_t maelys_sandbox_policy_plan_network_destination_at_ex( const maelys_sandbox_policy_plan_t *plan, size_t index, maelys_mir_network_destination_ex_view_t *out_destination);
int maelys_sandbox_policy_plan_process_tree_required( const maelys_sandbox_policy_plan_t *plan);
const char *maelys_sandbox_policy_plan_mir_digest(const maelys_sandbox_policy_plan_t *plan);

#endif
