/* Generated by scripts/freeze_abi.py from v0.4.1: include/maelys/mir.h.
 * Do not edit. Include after the current headers, once with
 * MAELYS_ABI_FLOOR_PRESENCE defined and once without. While this compiles,
 * every declaration of that revision still holds as it was: it is the
 * floor the ABI_COMPATIBLE_SINCE macro names. Regenerate only when a
 * break raises that floor, in the same change that raises the macro. */
#include <stddef.h>
#ifdef MAELYS_ABI_FLOOR_PRESENCE
void abi_mir_3_presence(void);
void abi_mir_3_presence(void) {
    (void)sizeof(maelys_mir_t *);
    (void)sizeof(maelys_mir_builder_t *);
    (void)sizeof(maelys_mir_result_t *);
    (void)sizeof(maelys_mir_fs_access_t *);
    (void)sizeof(maelys_mir_path_root_t *);
    (void)sizeof(maelys_mir_path_scope_t *);
    (void)sizeof(maelys_mir_missing_path_t *);
    (void)sizeof(maelys_mir_network_mode_t *);
    (void)sizeof(maelys_mir_network_protocol_t *);
    (void)sizeof(maelys_mir_root_mode_t *);
    (void)sizeof(maelys_mir_network_destination_view_t *);
    (void)sizeof(maelys_mir_fs_rule_view_t *);
    (void)maelys_mir_error_free;
    (void)maelys_mir_bytes_free;
    (void)maelys_mir_result_name;
    (void)maelys_mir_builder_create;
    (void)maelys_mir_builder_destroy;
    (void)maelys_mir_builder_add_fs_rule;
    (void)maelys_mir_builder_set_network;
    (void)maelys_mir_builder_set_root_mode;
    (void)maelys_mir_builder_add_network_destination;
    (void)maelys_mir_builder_set_process_tree_required;
    (void)maelys_mir_builder_build;
    (void)maelys_mir_destroy;
    (void)maelys_mir_fs_rule_count;
    (void)maelys_mir_fs_rule_at;
    (void)maelys_mir_network;
    (void)maelys_mir_root_mode;
    (void)maelys_mir_network_destination_count;
    (void)maelys_mir_network_destination_at;
    (void)maelys_mir_process_tree_required;
    (void)maelys_mir_encode;
    (void)maelys_mir_decode;
    (void)maelys_mir_check_canonical;
    (void)maelys_mir_digest_hex;
    (void)maelys_mir_artifact_digest_hex;
    (void)maelys_mir_inspect_json;
    (void)maelys_mir_restrict;
    (void)maelys_mir_compile_json;
}
#else

/* include/maelys/mir.h at v0.4.1 */
_Static_assert((MAELYS_MIR_FORMAT_VERSION) == (3u), "MAELYS_MIR_FORMAT_VERSION changed since v0.4.1");
_Static_assert((MAELYS_MIR_DIGEST_HEX_SIZE) == (65u), "MAELYS_MIR_DIGEST_HEX_SIZE changed since v0.4.1");
_Static_assert((MAELYS_MIR_INSPECTION_FORMAT_VERSION) == (1u), "MAELYS_MIR_INSPECTION_FORMAT_VERSION changed since v0.4.1");
_Static_assert((MAELYS_MIR_MAX_BYTES) == ((1024u * 1024u)), "MAELYS_MIR_MAX_BYTES changed since v0.4.1");
_Static_assert((MAELYS_MIR_MAX_RULES) == (4096u), "MAELYS_MIR_MAX_RULES changed since v0.4.1");
_Static_assert((MAELYS_MIR_MAX_STRING_BYTES) == (4096u), "MAELYS_MIR_MAX_STRING_BYTES changed since v0.4.1");
_Static_assert((MAELYS_MIR_MAX_NETWORK_DESTINATIONS) == (1024u), "MAELYS_MIR_MAX_NETWORK_DESTINATIONS changed since v0.4.1");
_Static_assert((MAELYS_MIR_MAX_NETWORK_HOST_BYTES) == (253u), "MAELYS_MIR_MAX_NETWORK_HOST_BYTES changed since v0.4.1");
typedef struct maelys_mir maelys_mir_t;
typedef struct maelys_mir_builder maelys_mir_builder_t;
_Static_assert(MAELYS_MIR_OK == (0) + 0, "MAELYS_MIR_OK moved since v0.4.1");
_Static_assert(MAELYS_MIR_ERR_ARGUMENT == (1) + 0, "MAELYS_MIR_ERR_ARGUMENT moved since v0.4.1");
_Static_assert(MAELYS_MIR_ERR_MEMORY == (2) + 0, "MAELYS_MIR_ERR_MEMORY moved since v0.4.1");
_Static_assert(MAELYS_MIR_ERR_FORMAT == (3) + 0, "MAELYS_MIR_ERR_FORMAT moved since v0.4.1");
_Static_assert(MAELYS_MIR_ERR_LIMIT == (4) + 0, "MAELYS_MIR_ERR_LIMIT moved since v0.4.1");
_Static_assert(MAELYS_MIR_ERR_NON_CANONICAL == (5) + 0, "MAELYS_MIR_ERR_NON_CANONICAL moved since v0.4.1");
_Static_assert(MAELYS_MIR_ERR_IO == (6) + 0, "MAELYS_MIR_ERR_IO moved since v0.4.1");
_Static_assert(MAELYS_MIR_ERR_UNSUPPORTED == (7) + 0, "MAELYS_MIR_ERR_UNSUPPORTED moved since v0.4.1");
_Static_assert(MAELYS_MIR_ERR_MISSING == (8) + 0, "MAELYS_MIR_ERR_MISSING moved since v0.4.1");
_Static_assert(MAELYS_MIR_FS_READ == (1) + 0, "MAELYS_MIR_FS_READ moved since v0.4.1");
_Static_assert(MAELYS_MIR_FS_WRITE == (2) + 0, "MAELYS_MIR_FS_WRITE moved since v0.4.1");
_Static_assert(MAELYS_MIR_FS_DENY == (3) + 0, "MAELYS_MIR_FS_DENY moved since v0.4.1");
_Static_assert(MAELYS_MIR_ROOT_MINIMAL_RUNTIME == (1) + 0, "MAELYS_MIR_ROOT_MINIMAL_RUNTIME moved since v0.4.1");
_Static_assert(MAELYS_MIR_ROOT_WORKSPACE == (2) + 0, "MAELYS_MIR_ROOT_WORKSPACE moved since v0.4.1");
_Static_assert(MAELYS_MIR_ROOT_TEMP == (3) + 0, "MAELYS_MIR_ROOT_TEMP moved since v0.4.1");
_Static_assert(MAELYS_MIR_ROOT_HOST == (4) + 0, "MAELYS_MIR_ROOT_HOST moved since v0.4.1");
_Static_assert(MAELYS_MIR_SCOPE_EXACT == (1) + 0, "MAELYS_MIR_SCOPE_EXACT moved since v0.4.1");
_Static_assert(MAELYS_MIR_SCOPE_TREE == (2) + 0, "MAELYS_MIR_SCOPE_TREE moved since v0.4.1");
_Static_assert(MAELYS_MIR_MISSING_ERROR == (1) + 0, "MAELYS_MIR_MISSING_ERROR moved since v0.4.1");
_Static_assert(MAELYS_MIR_MISSING_SKIP == (2) + 0, "MAELYS_MIR_MISSING_SKIP moved since v0.4.1");
_Static_assert(MAELYS_MIR_NETWORK_NONE == (1) + 0, "MAELYS_MIR_NETWORK_NONE moved since v0.4.1");
_Static_assert(MAELYS_MIR_NETWORK_DIRECT == (2) + 0, "MAELYS_MIR_NETWORK_DIRECT moved since v0.4.1");
_Static_assert(MAELYS_MIR_NETWORK_MEDIATED == (3) + 0, "MAELYS_MIR_NETWORK_MEDIATED moved since v0.4.1");
_Static_assert(MAELYS_MIR_NETWORK_PROTOCOL_TCP == (1) + 0, "MAELYS_MIR_NETWORK_PROTOCOL_TCP moved since v0.4.1");
_Static_assert(MAELYS_MIR_ROOT_READ_ONLY == (1) + 0, "MAELYS_MIR_ROOT_READ_ONLY moved since v0.4.1");
_Static_assert(MAELYS_MIR_ROOT_EPHEMERAL_WRITE == (2) + 0, "MAELYS_MIR_ROOT_EPHEMERAL_WRITE moved since v0.4.1");
typedef struct frozen_maelys_mir_network_destination_view {
    maelys_mir_network_protocol_t protocol;
    const char *host;
    uint16_t port;
} frozen_maelys_mir_network_destination_view_t;
_Static_assert(sizeof(maelys_mir_network_destination_view_t) == sizeof(frozen_maelys_mir_network_destination_view_t), "maelys_mir_network_destination_view_t changed size since v0.4.1");
_Static_assert(offsetof(maelys_mir_network_destination_view_t, protocol) == offsetof(frozen_maelys_mir_network_destination_view_t, protocol), "maelys_mir_network_destination_view_t.protocol moved since v0.4.1");
_Static_assert(offsetof(maelys_mir_network_destination_view_t, host) == offsetof(frozen_maelys_mir_network_destination_view_t, host), "maelys_mir_network_destination_view_t.host moved since v0.4.1");
_Static_assert(offsetof(maelys_mir_network_destination_view_t, port) == offsetof(frozen_maelys_mir_network_destination_view_t, port), "maelys_mir_network_destination_view_t.port moved since v0.4.1");
typedef struct frozen_maelys_mir_fs_rule_view {
    maelys_mir_fs_access_t access;
    maelys_mir_path_root_t root;
    maelys_mir_path_scope_t scope;
    maelys_mir_missing_path_t missing;
    const char *relative;
} frozen_maelys_mir_fs_rule_view_t;
_Static_assert(sizeof(maelys_mir_fs_rule_view_t) == sizeof(frozen_maelys_mir_fs_rule_view_t), "maelys_mir_fs_rule_view_t changed size since v0.4.1");
_Static_assert(offsetof(maelys_mir_fs_rule_view_t, access) == offsetof(frozen_maelys_mir_fs_rule_view_t, access), "maelys_mir_fs_rule_view_t.access moved since v0.4.1");
_Static_assert(offsetof(maelys_mir_fs_rule_view_t, root) == offsetof(frozen_maelys_mir_fs_rule_view_t, root), "maelys_mir_fs_rule_view_t.root moved since v0.4.1");
_Static_assert(offsetof(maelys_mir_fs_rule_view_t, scope) == offsetof(frozen_maelys_mir_fs_rule_view_t, scope), "maelys_mir_fs_rule_view_t.scope moved since v0.4.1");
_Static_assert(offsetof(maelys_mir_fs_rule_view_t, missing) == offsetof(frozen_maelys_mir_fs_rule_view_t, missing), "maelys_mir_fs_rule_view_t.missing moved since v0.4.1");
_Static_assert(offsetof(maelys_mir_fs_rule_view_t, relative) == offsetof(frozen_maelys_mir_fs_rule_view_t, relative), "maelys_mir_fs_rule_view_t.relative moved since v0.4.1");
void maelys_mir_error_free(char *error);
void maelys_mir_bytes_free(uint8_t *bytes);
const char *maelys_mir_result_name(maelys_mir_result_t result);
maelys_mir_result_t maelys_mir_builder_create(maelys_mir_builder_t **out_builder, char **out_error);
void maelys_mir_builder_destroy(maelys_mir_builder_t *builder);
maelys_mir_result_t maelys_mir_builder_add_fs_rule( maelys_mir_builder_t *builder, maelys_mir_fs_access_t access, maelys_mir_path_root_t root, const char *relative, maelys_mir_path_scope_t scope, maelys_mir_missing_path_t missing, char **out_error);
maelys_mir_result_t maelys_mir_builder_set_network(maelys_mir_builder_t *builder, maelys_mir_network_mode_t mode, char **out_error);
maelys_mir_result_t maelys_mir_builder_set_root_mode(maelys_mir_builder_t *builder, maelys_mir_root_mode_t mode, char **out_error);
maelys_mir_result_t maelys_mir_builder_add_network_destination( maelys_mir_builder_t *builder, maelys_mir_network_protocol_t protocol, const char *host, uint16_t port, char **out_error);
maelys_mir_result_t maelys_mir_builder_set_process_tree_required(maelys_mir_builder_t *builder, int required, char **out_error);
maelys_mir_result_t maelys_mir_builder_build(maelys_mir_builder_t *builder, maelys_mir_t **out_mir, char **out_error);
void maelys_mir_destroy(maelys_mir_t *mir);
size_t maelys_mir_fs_rule_count(const maelys_mir_t *mir);
maelys_mir_result_t maelys_mir_fs_rule_at(const maelys_mir_t *mir, size_t index, maelys_mir_fs_rule_view_t *out_rule);
maelys_mir_network_mode_t maelys_mir_network(const maelys_mir_t *mir);
maelys_mir_root_mode_t maelys_mir_root_mode(const maelys_mir_t *mir);
size_t maelys_mir_network_destination_count(const maelys_mir_t *mir);
maelys_mir_result_t maelys_mir_network_destination_at( const maelys_mir_t *mir, size_t index, maelys_mir_network_destination_view_t *out_destination);
int maelys_mir_process_tree_required(const maelys_mir_t *mir);
maelys_mir_result_t maelys_mir_encode(const maelys_mir_t *mir, uint8_t **out_bytes, size_t *out_size, char **out_error);
maelys_mir_result_t maelys_mir_decode(const uint8_t *bytes, size_t size, maelys_mir_t **out_mir, char **out_error);
maelys_mir_result_t maelys_mir_check_canonical(const uint8_t *bytes, size_t size, char **out_error);
maelys_mir_result_t maelys_mir_digest_hex(const maelys_mir_t *mir, char out_hex[MAELYS_MIR_DIGEST_HEX_SIZE], char **out_error);
maelys_mir_result_t maelys_mir_artifact_digest_hex( const uint8_t *bytes, size_t size, char out_hex[MAELYS_MIR_DIGEST_HEX_SIZE], char **out_error);
maelys_mir_result_t maelys_mir_inspect_json(const maelys_mir_t *mir, uint8_t **out_json, size_t *out_size, char **out_error);
maelys_mir_result_t maelys_mir_restrict(const maelys_mir_t *base, const maelys_mir_t *restriction, maelys_mir_t **out_effective, char **out_error);
maelys_mir_result_t maelys_mir_compile_json(const uint8_t *json, size_t size, maelys_mir_t **out_mir, char **out_error);

#endif
