/*
 * A consumer as it compiled against the headers of Sandbox Policy 0.9.0,
 * frozen.
 *
 * Each switch below names every enumerator a public enumeration had at that
 * release and has NO default, the way a consumer built with -Werror=switch
 * may be written. It is compiled, not run, against the current headers.
 *
 * DO NOT edit this file to make it compile. When it stops compiling, an
 * enumerator was added to a public enumeration: that keeps the ABI floor
 * and breaks such a consumer's build. The change may still be right. Make
 * it a decision: add the enumerator here, re-freeze the release named
 * above, AND write a "Consumer notice" line in CHANGELOG.md saying which
 * enumeration grew.
 */
#include <maelys/mir.h>
#include <maelys/sandbox_policy.h>

int frozen_mir_result(maelys_mir_result_t value);
int frozen_fs_access(maelys_mir_fs_access_t value);
int frozen_path_root(maelys_mir_path_root_t value);
int frozen_path_scope(maelys_mir_path_scope_t value);
int frozen_missing_path(maelys_mir_missing_path_t value);
int frozen_network_mode(maelys_mir_network_mode_t value);
int frozen_network_protocol(maelys_mir_network_protocol_t value);
int frozen_root_mode(maelys_mir_root_mode_t value);
int frozen_plan_missing(maelys_sandbox_policy_missing_t value);
int frozen_permission(maelys_sandbox_policy_permission_t value);
int frozen_reason(maelys_sandbox_policy_reason_t value);
int frozen_network_excess(maelys_sandbox_policy_network_excess_t value);

int frozen_mir_result(maelys_mir_result_t value) {
  switch (value) {
  case MAELYS_MIR_OK: return 0;
  case MAELYS_MIR_ERR_ARGUMENT: return 1;
  case MAELYS_MIR_ERR_MEMORY: return 1;
  case MAELYS_MIR_ERR_FORMAT: return 1;
  case MAELYS_MIR_ERR_LIMIT: return 1;
  case MAELYS_MIR_ERR_NON_CANONICAL: return 1;
  case MAELYS_MIR_ERR_IO: return 1;
  case MAELYS_MIR_ERR_UNSUPPORTED: return 1;
  case MAELYS_MIR_ERR_MISSING: return 1;
  case MAELYS_MIR_ERR_CONFLICT: return 1;
  }
  return -1;
}

int frozen_fs_access(maelys_mir_fs_access_t value) {
  switch (value) {
  case MAELYS_MIR_FS_READ: return 1;
  case MAELYS_MIR_FS_WRITE: return 2;
  case MAELYS_MIR_FS_DENY: return 3;
  case MAELYS_MIR_FS_DENY_WRITE: return 4;
  }
  return -1;
}

int frozen_path_root(maelys_mir_path_root_t value) {
  switch (value) {
  case MAELYS_MIR_ROOT_MINIMAL_RUNTIME: return 1;
  case MAELYS_MIR_ROOT_WORKSPACE: return 2;
  case MAELYS_MIR_ROOT_TEMP: return 3;
  case MAELYS_MIR_ROOT_HOST: return 4;
  }
  return -1;
}

int frozen_path_scope(maelys_mir_path_scope_t value) {
  switch (value) {
  case MAELYS_MIR_SCOPE_EXACT: return 1;
  case MAELYS_MIR_SCOPE_TREE: return 2;
  }
  return -1;
}

int frozen_missing_path(maelys_mir_missing_path_t value) {
  switch (value) {
  case MAELYS_MIR_MISSING_ERROR: return 1;
  case MAELYS_MIR_MISSING_SKIP: return 2;
  }
  return -1;
}

int frozen_network_mode(maelys_mir_network_mode_t value) {
  switch (value) {
  case MAELYS_MIR_NETWORK_NONE: return 1;
  case MAELYS_MIR_NETWORK_DIRECT: return 2;
  case MAELYS_MIR_NETWORK_MEDIATED: return 3;
  }
  return -1;
}

int frozen_network_protocol(maelys_mir_network_protocol_t value) {
  switch (value) {
  case MAELYS_MIR_NETWORK_PROTOCOL_TCP: return 1;
  }
  return -1;
}

int frozen_root_mode(maelys_mir_root_mode_t value) {
  switch (value) {
  case MAELYS_MIR_ROOT_READ_ONLY: return 1;
  case MAELYS_MIR_ROOT_EPHEMERAL_WRITE: return 2;
  }
  return -1;
}

int frozen_plan_missing(maelys_sandbox_policy_missing_t value) {
  switch (value) {
  case MAELYS_SANDBOX_POLICY_MISSING_ERROR: return 1;
  case MAELYS_SANDBOX_POLICY_MISSING_PROTECT_CREATE: return 2;
  }
  return -1;
}

int frozen_permission(maelys_sandbox_policy_permission_t value) {
  switch (value) {
  case MAELYS_SANDBOX_POLICY_PERMISSION_NONE: return 0;
  case MAELYS_SANDBOX_POLICY_PERMISSION_READ: return 1;
  case MAELYS_SANDBOX_POLICY_PERMISSION_READ_WRITE: return 2;
  }
  return -1;
}

int frozen_reason(maelys_sandbox_policy_reason_t value) {
  switch (value) {
  case MAELYS_SANDBOX_POLICY_REASON_DEFAULT_DENY: return 1;
  case MAELYS_SANDBOX_POLICY_REASON_DENY_RULE: return 2;
  case MAELYS_SANDBOX_POLICY_REASON_WRITE_RULE: return 3;
  case MAELYS_SANDBOX_POLICY_REASON_READ_RULE: return 4;
  case MAELYS_SANDBOX_POLICY_REASON_DENY_WRITE_RULE: return 5;
  }
  return -1;
}

int frozen_network_excess(maelys_sandbox_policy_network_excess_t value) {
  switch (value) {
  case MAELYS_SANDBOX_POLICY_NETWORK_EXCESS_NONE: return 0;
  case MAELYS_SANDBOX_POLICY_NETWORK_EXCESS_MODE: return 1;
  case MAELYS_SANDBOX_POLICY_NETWORK_EXCESS_DESTINATION: return 2;
  case MAELYS_SANDBOX_POLICY_NETWORK_EXCESS_TLS_SNI: return 3;
  case MAELYS_SANDBOX_POLICY_NETWORK_EXCESS_PRIVATE_ADDRESSES: return 4;
  }
  return -1;
}
