#!/usr/bin/env python3
# SPDX-License-Identifier: MPL-2.0
"""Freeze the public declarations of a tagged revision into a checkable header.

Reads public headers as they were at a tag and writes a C fragment that is
included AFTER the current headers, twice. With MAELYS_ABI_FLOOR_PRESENCE
defined it names every function and type of the revision, which a compiler
refuses if the current headers no longer declare one: a declaration made
again below would otherwise hide a removal. Without the macro, every function
prototype and opaque typedef is declared again, which a compiler refuses if
the current one differs; every enumerator and numeric macro becomes a static
assertion on its value; every open structure is copied under a frozen name
and compared by size and by the offset of each member. The fragment is
committed. It is the
floor MAELYS_*_ABI_COMPATIBLE_SINCE names: while it compiles, nothing a
consumer written for that revision uses has changed.

Run once, when a break raises the floor:

    python3 scripts/freeze_abi.py TAG OUTPUT HEADER [HEADER...]
"""
import re
import subprocess
import sys

# The two numbers themselves are not part of the floor: the revision rises
# with every addition, and the floor macro is what this fragment stands for.
SKIP_MACRO = re.compile(r"_ABI_(VERSION|COMPATIBLE_SINCE)$")


def header_at(tag: str, path: str) -> str:
    return subprocess.run(["git", "show", f"{tag}:{path}"], check=True,
                          capture_output=True, text=True).stdout


def strip_comments(text: str) -> str:
    text = re.sub(r"/\*.*?\*/", " ", text, flags=re.S)
    return re.sub(r"//[^\n]*", " ", text)


def macros(text: str):
    joined = re.sub(r"\\\n", " ", text)
    for match in re.finditer(r"^#define[ \t]+(MAELYS_[A-Z0-9_]+)[ \t]+(.+)$", joined, re.M):
        name, value = match.group(1), " ".join(match.group(2).split())
        # A string, such as the product version, is no part of an interface:
        # it is meant to change with every release.
        if not SKIP_MACRO.search(name) and not value.startswith('"'):
            yield name, value


def statements(text: str):
    text = re.sub(r"\\\n", " ", text)  # a continued #define is one line
    text = "\n".join(line for line in text.splitlines()
                     if not line.lstrip().startswith("#")
                     and line.strip() not in ('extern "C" {', "}"))
    depth, start = 0, 0
    for index, char in enumerate(text):
        if char in "{(":
            depth += 1
        elif char in "})":
            depth -= 1
        elif char == ";" and depth == 0:
            statement = " ".join(text[start:index].split())
            start = index + 1
            if statement:
                yield statement


def enumerators(body: str):
    base, offset = "0", 0
    for item in (part.strip() for part in body.split(",")):
        if not item:
            continue
        if "=" in item:
            name, base = (side.strip() for side in item.split("=", 1))
            offset = 0
        else:
            name = item
        yield name, f"({base}) + {offset}"
        offset += 1


def members(body: str):
    depth, start = 0, 0
    for index, char in enumerate(body):
        if char == "(":
            depth += 1
        elif char == ")":
            depth -= 1
        elif char == ";" and depth == 0:
            member = body[start:index].strip()
            start = index + 1
            pointer = re.search(r"\(\s*\*\s*([a-z_0-9]+)\s*\)", member)
            name = pointer.group(1) if pointer else re.sub(
                r"\[[^\]]*\]$", "", member).split()[-1].lstrip("*")
            yield member, name


def main() -> int:
    tag, output, paths = sys.argv[1], sys.argv[2], sys.argv[3:]
    out = [
        f"/* Generated by scripts/freeze_abi.py from {tag}: {' '.join(paths)}.",
        " * Do not edit. Include after the current headers, once with",
        " * MAELYS_ABI_FLOOR_PRESENCE defined and once without. While this compiles,",
        " * every declaration of that revision still holds as it was: it is the",
        " * floor the ABI_COMPATIBLE_SINCE macro names. Regenerate only when a",
        " * break raises that floor, in the same change that raises the macro. */",
        "#include <stddef.h>",
        "",
    ]
    present_functions, present_types = [], []
    for path in paths:
        raw = header_at(tag, path)
        text = strip_comments(raw)
        out.append(f"/* {path} at {tag} */")
        for name, value in macros(text):
            out.append(f'_Static_assert(({name}) == ({value}), "{name} changed since {tag}");')
        for statement in statements(text):
            enum = re.match(r"typedef enum [a-z_0-9]+ \{(.*)\} ([a-z_0-9]+)$", statement)
            struct = re.match(r"typedef struct ([a-z_0-9]+) \{(.*)\} ([a-z_0-9]+)$", statement)
            if enum:
                present_types.append(enum.group(2))
                for name, value in enumerators(enum.group(1)):
                    out.append(f'_Static_assert({name} == {value}, "{name} moved since {tag}");')
            elif re.match(r"enum \{(.*)\}$", statement):
                # An enumeration without a name, used for its constants: there
                # is no type to hold, only the value of each constant.
                for name, value in enumerators(re.match(r"enum \{(.*)\}$", statement).group(1)):
                    out.append(f'_Static_assert({name} == {value}, "{name} moved since {tag}");')
            elif struct:
                tag_name, body, alias = struct.groups()
                present_types.append(alias)
                frozen = f"frozen_{alias}"
                fields = list(members(body))
                out.append(f"typedef struct frozen_{tag_name} {{")
                out.extend(f"    {member};" for member, _ in fields)
                out.append(f"}} {frozen};")
                out.append(f'_Static_assert(sizeof({alias}) == sizeof({frozen}), '
                           f'"{alias} changed size since {tag}");')
                for _, name in fields:
                    out.append(f'_Static_assert(offsetof({alias}, {name}) == '
                               f'offsetof({frozen}, {name}), "{alias}.{name} moved since {tag}");')
            else:
                out.append(statement + ";")
                if statement.startswith("typedef "):
                    alias = re.search(r"\(\s*\*\s*([a-z_0-9]+)\s*\)|([a-z_0-9]+)$", statement)
                    present_types.append(alias.group(1) or alias.group(2))
                else:
                    present_functions.append(re.search(r"([a-z_0-9]+)\s*\(", statement).group(1))
        out.append("")
    stem = re.sub(r"[^a-z0-9]+", "_", output.rsplit("/", 1)[-1].rsplit(".", 1)[0])
    presence = ["#ifdef MAELYS_ABI_FLOOR_PRESENCE",
                f"void {stem}_presence(void);",
                f"void {stem}_presence(void) {{"]
    presence.extend(f"    (void)sizeof({name} *);" for name in present_types)
    presence.extend(f"    (void){name};" for name in present_functions)
    presence.extend(["}", "#else"])
    out = out[:7] + presence + out[7:] + ["#endif", ""]
    with open(output, "w", encoding="utf-8") as stream:
        stream.write("\n".join(out))
    declarations = sum(1 for line in out if line.endswith(";") and not line.startswith(("_Static", "    ", "}")))
    assertions = sum(1 for line in out if line.startswith("_Static"))
    print(f"{output}: {declarations} declarations, {assertions} assertions from {tag}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
